// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AffiliateChartController from "./affiliate_chart_controller"
application.register("affiliate-chart", AffiliateChartController)

import BulkSelectController from "./bulk_select_controller"
application.register("bulk-select", BulkSelectController)

import ContactSelectionController from "./contact_selection_controller"
application.register("contact-selection", ContactSelectionController)

import CopyToClipboardController from "./copy_to_clipboard_controller"
application.register("copy-to-clipboard", CopyToClipboardController)

import FilterTableController from "./filter_table_controller"
application.register("filter-table", FilterTableController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PayoutCalculatorController from "./payout_calculator_controller"
application.register("payout-calculator", PayoutCalculatorController)

import QrCodeController from "./qr_code_controller"
application.register("qr-code", QrCodeController)

import ScoutController from "./scout_controller"
application.register("scout", ScoutController)

import TurboFormController from "./turbo_form_controller"
application.register("turbo-form", TurboFormController)

import VoiceAssistantController from "./voice_assistant_controller"
application.register("voice-assistant", VoiceAssistantController)

import VoiceSettingsController from "./voice_settings_controller"
application.register("voice-settings", VoiceSettingsController)

import ProfileEditorController from "./profile_editor_controller"
application.register("profile-editor", ProfileEditorController)
