// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AffiliateChartController from "./affiliate_chart_controller"
application.register("affiliate-chart", AffiliateChartController)

import BulkSelectController from "./bulk_select_controller"
application.register("bulk-select", BulkSelectController)

import ContactSelectionController from "./contact_selection_controller"
application.register("contact-selection", ContactSelectionController)

import CopyToClipboardController from "./copy_to_clipboard_controller"
application.register("copy-to-clipboard", CopyToClipboardController)

import FeedbackController from "./feedback_controller"
application.register("feedback", FeedbackController)

import FilterTableController from "./filter_table_controller"
application.register("filter-table", FilterTableController)

import PayoutCalculatorController from "./payout_calculator_controller"
application.register("payout-calculator", PayoutCalculatorController)

import QrCodeController from "./qr_code_controller"
application.register("qr-code", QrCodeController)

import ScoutController from "./scout_controller"
application.register("scout", ScoutController)

import SpaceSwitcherController from "./space_switcher_controller"
application.register("space-switcher", SpaceSwitcherController)

import TurboFormController from "./turbo_form_controller"
application.register("turbo-form", TurboFormController)

import VoiceAssistantController from "./voice_assistant_controller"
application.register("voice-assistant", VoiceAssistantController)

import VoiceSettingsController from "./voice_settings_controller"
application.register("voice-settings", VoiceSettingsController)

import WebPageViewerController from "./web_page_viewer_controller"
application.register("web-page-viewer", WebPageViewerController)

import ProfileEditorController from "./profile_editor_controller"
application.register("profile-editor", ProfileEditorController)

import QuestionQueueController from "./question_queue_controller"
application.register("question-queue", QuestionQueueController)

import HubSidebarController from "./hub_sidebar_controller"
application.register("hub-sidebar", HubSidebarController)

import ModuleCanvasController from "./module_canvas_controller"
application.register("module-canvas", ModuleCanvasController)
// Also register aliases for legacy canvas types
application.register("module-report", ModuleCanvasController)
application.register("module-form", ModuleCanvasController)
application.register("module-data-grid", ModuleCanvasController)

import ModuleMarketplaceController from "./module_marketplace_controller"
application.register("module-marketplace", ModuleMarketplaceController)

import ModuleDesignController from "./module_design_controller"
application.register("module-design", ModuleDesignController)

import ModeSwitcherController from "./mode_switcher_controller"
application.register("mode-switcher", ModeSwitcherController)

import DesignPanelController from "./design_panel_controller"
application.register("design-panel", DesignPanelController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import DesignChatController from "./design_chat_controller"
application.register("design-chat", DesignChatController)
