// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TurboFormController from "./turbo_form_controller"
application.register("turbo-form", TurboFormController)

import ContactSelectionController from "./contact_selection_controller"
application.register("contact-selection", ContactSelectionController)

import LandingPageChatController from "./landing_page/chat"
application.register("landing-page-chat", LandingPageChatController)
