class IntegrationScaffoldService
  def generate_scaffold(app_name:, slug:, auth_type:, base_url: nil, description: nil, entity:, user:)
    Rails.logger.info "🏗️ Generating integration scaffold for #{app_name}"
    
    begin
      files_created = []
      
      # 1. Create Integration record
      integration = create_integration_record(
        app_name: app_name,
        slug: slug,
        auth_type: auth_type,
        base_url: base_url,
        description: description,
        entity: entity
      )
      
      # 2. Create directory structure
      base_dir = Rails.root.join('app', 'services', 'integrations', slug)
      FileUtils.mkdir_p(base_dir)
      
      # 3. Generate base service file
      service_file = generate_base_service(integration, base_dir)
      files_created << service_file
      
      # 4. Generate auth module
      auth_file = generate_auth_module(integration, base_dir)
      files_created << auth_file
      
      # 5. Generate error handler
      error_file = generate_error_handler(integration, base_dir)
      files_created << error_file
      
      # 6. Generate operations file (empty scaffold)
      operations_file = generate_operations_file(integration, base_dir)
      files_created << operations_file
      
      # 7. Create initial connection for the user
      connection = create_initial_connection(integration, entity, user)
      
      # 8. Run auto-discovery to register operations
      Rails.logger.info "🔍 Running auto-discovery for new integration..."
      OperationDiscoveryService.discover_integration(integration.slug)
      
      {
        success: true,
        integration_id: integration.id,
        connection_id: connection.id,
        files_created: files_created,
        scaffold_path: base_dir.to_s
      }
    rescue => e
      Rails.logger.error "Scaffold generation failed: #{e.message}"
      Rails.logger.error e.backtrace.join("\n")
      { success: false, error: e.message }
    end
  end
  
  private
  
  def create_integration_record(app_name:, slug:, auth_type:, base_url:, description:, entity:)
    Integration.create!(
      name: app_name,
      slug: slug,
      description: description || "Integration with #{app_name}",
      category: 'custom',
      auth_type: auth_type,
      api_base_url: base_url || "https://api.#{slug}.com",
      is_active: true,
      is_custom: true,
      metadata: {
        created_by: 'ai_integration_builder',
        auth_type: auth_type
      }
    )
  end
  
  def generate_base_service(integration, base_dir)
    file_path = base_dir.join("#{integration.slug}_service.rb")
    
    code = <<~RUBY
      # #{integration.name} Integration Service
      # Generated by AI Integration Builder
      
      module Integrations
        module #{integration.slug.camelize}
          class #{integration.slug.camelize}Service < Integrations::BaseService
            def initialize(connection)
              super(connection)
              @auth = #{integration.slug.camelize}Auth.new(connection)
            end
            
            # Universal executor will call this method
            def execute_operation(operation_id, params = {})
              # Try to find and call the method
              method_name = operation_id.to_sym
              
              if respond_to?(method_name, true)
                send(method_name, **params.symbolize_keys)
              else
                { success: false, error: "Operation '\#{operation_id}' not found" }
              end
            end
            
            # List available operations (for discovery)
            def available_operations
              # Get all public methods excluding base class methods
              base_methods = Integrations::BaseService.instance_methods
              (self.class.instance_methods(false) - base_methods).map(&:to_s)
            end
            
            # Override base_url if needed
            def base_url
              '#{integration.api_base_url || "https://api.#{integration.slug}.com"}'
            end
            
            # Override authentication_headers if needed
            # def authentication_headers
            #   # Custom authentication logic
            #   super
            # end
          end
        end
      end
    RUBY
    
    File.write(file_path, code)
    file_path.to_s
  end
  
  def generate_auth_module(integration, base_dir)
    file_path = base_dir.join("#{integration.slug}_auth.rb")
    
    code = case integration.auth_type
    when 'oauth2'
      generate_oauth2_auth(integration)
    when 'api_key'
      generate_api_key_auth(integration)
    when 'bearer_token'
      generate_bearer_token_auth(integration)
    when 'basic_auth'
      generate_basic_auth(integration)
    else
      generate_api_key_auth(integration) # Default
    end
    
    File.write(file_path, code)
    file_path.to_s
  end
  
  def generate_oauth2_auth(integration)
    <<~RUBY
      # OAuth2 Authentication for #{integration.name}
      
      module Integrations
        module #{integration.slug.camelize}
          class #{integration.slug.camelize}Auth
            attr_reader :connection
            
            def initialize(connection)
              @connection = connection
            end
            
            def headers
              {
                'Authorization' => "Bearer \#{access_token}",
                'Content-Type' => 'application/json',
                'Accept' => 'application/json'
              }
            end
            
            def access_token
              # Check if token is expired
              if token_expired?
                refresh_token!
              end
              
              credential = @connection.active_credential
              return nil unless credential
              
              credential.credentials['access_token']
            end
            
            private
            
            def token_expired?
              credential = @connection.active_credential
              return true unless credential
              
              credential.expired? || credential.needs_refresh?
            end
            
            def refresh_token!
              # TODO: Implement OAuth2 token refresh
              # This will be customized based on the specific API
              Rails.logger.warn "OAuth2 token refresh not yet implemented for #{integration.name}"
            end
          end
        end
      end
    RUBY
  end
  
  def generate_api_key_auth(integration)
    <<~RUBY
      # API Key Authentication for #{integration.name}
      
      module Integrations
        module #{integration.slug.camelize}
          class #{integration.slug.camelize}Auth
            attr_reader :connection
            
            def initialize(connection)
              @connection = connection
            end
            
            def headers
              {
                'Authorization' => api_key_header,
                'Content-Type' => 'application/json',
                'Accept' => 'application/json'
              }
            end
            
            private
            
            def api_key_header
              # Common patterns - customize based on API requirements
              credential = @connection.active_credential
              return '' unless credential
              
              api_key = credential.credentials['api_key']
              
              # Try different header formats (customize for specific API)
              "Bearer \#{api_key}"
              # OR: "Api-Key \#{api_key}"
              # OR: just return the key if it goes in a custom header
            end
          end
        end
      end
    RUBY
  end
  
  def generate_bearer_token_auth(integration)
    <<~RUBY
      # Bearer Token Authentication for #{integration.name}
      
      module Integrations
        module #{integration.slug.camelize}
          class #{integration.slug.camelize}Auth
            attr_reader :connection
            
            def initialize(connection)
              @connection = connection
            end
            
            def headers
              {
                'Authorization' => "Bearer \#{bearer_token}",
                'Content-Type' => 'application/json',
                'Accept' => 'application/json'
              }
            end
            
            private
            
            def bearer_token
              credential = @connection.active_credential
              return nil unless credential
              
              credential.credentials['bearer_token'] || 
              credential.credentials['token']
            end
          end
        end
      end
    RUBY
  end
  
  def generate_basic_auth(integration)
    <<~RUBY
      # Basic Authentication for #{integration.name}
      
      module Integrations
        module #{integration.slug.camelize}
          class #{integration.slug.camelize}Auth
            attr_reader :connection
            
            def initialize(connection)
              @connection = connection
            end
            
            def headers
              {
                'Authorization' => basic_auth_header,
                'Content-Type' => 'application/json',
                'Accept' => 'application/json'
              }
            end
            
            private
            
            def basic_auth_header
              credential = @connection.active_credential
              return '' unless credential
              
              username = credential.credentials['username']
              password = credential.credentials['password']
              credentials = Base64.strict_encode64("\#{username}:\#{password}")
              "Basic \#{credentials}"
            end
          end
        end
      end
    RUBY
  end
  
  def generate_error_handler(integration, base_dir)
    file_path = base_dir.join("error_handler.rb")
    
    code = <<~RUBY
      # Error Handler for #{integration.name} Integration
      
      module Integrations
        module #{integration.slug.camelize}
          class ErrorHandler
            def self.handle(error)
              case error
              when RestClient::Unauthorized
                {
                  success: false,
                  error: 'Authentication failed',
                  error_type: 'unauthorized',
                  message: 'Invalid or expired credentials',
                  status: 401
                }
              when RestClient::Forbidden
                {
                  success: false,
                  error: 'Access forbidden',
                  error_type: 'forbidden',
                  message: 'You do not have permission to access this resource',
                  status: 403
                }
              when RestClient::NotFound
                {
                  success: false,
                  error: 'Resource not found',
                  error_type: 'not_found',
                  message: 'The requested resource does not exist',
                  status: 404
                }
              when RestClient::TooManyRequests
                {
                  success: false,
                  error: 'Rate limit exceeded',
                  error_type: 'rate_limit',
                  message: 'Too many requests. Please try again later.',
                  status: 429,
                  retry_after: error.response.headers[:retry_after]
                }
              when RestClient::BadRequest
                {
                  success: false,
                  error: 'Bad request',
                  error_type: 'bad_request',
                  message: parse_error_message(error.response),
                  status: 400
                }
              else
                {
                  success: false,
                  error: 'API request failed',
                  error_type: 'unknown',
                  message: error.message,
                  status: error.try(:response)&.code || 500
                }
              end
            end
            
            private
            
            def self.parse_error_message(response)
              JSON.parse(response.body)['message'] rescue response.body
            end
          end
        end
      end
    RUBY
    
    File.write(file_path, code)
    file_path.to_s
  end
  
  def generate_operations_file(integration, base_dir)
    file_path = base_dir.join("operations.rb")
    
    code = <<~RUBY
      # Operations for #{integration.name} Integration
      # Add your API endpoint methods here
      
      module Integrations
        module #{integration.slug.camelize}
          module Operations
            # Example operation:
            # def get_user(user_id)
            #   request(:get, "/users/\#{user_id}")
            # end
            
            # Add your operations below:
            
          end
        end
      end
      
      # Include operations in the main service
      Integrations::#{integration.slug.camelize}::#{integration.slug.camelize}Service.include(
        Integrations::#{integration.slug.camelize}::Operations
      )
    RUBY
    
    File.write(file_path, code)
    file_path.to_s
  end
  
  def create_initial_connection(integration, entity, user)
    connection = Connection.create!(
      integration: integration,
      entity: entity,
      name: "#{integration.name} Connection",
      status: :disconnected,
      metadata: {
        created_by: 'ai_integration_builder',
        setup_required: true
      }
    )
    
    # Create pending credential record
    connection.integration_credentials.create!(
      name: "#{integration.name} Credentials",
      credentials: {}.to_json,
      auth_method: 'header',
      status: :expired,
      metadata: {
        pending_setup: true
      }
    )
    
    connection
  end
end

