# frozen_string_literal: true

module Api
  class AuthController < ApplicationController
    skip_before_action :authenticate_user!, only: [:login, :register, :verify_mfa, :login_with_device_token, :refresh_token, :resend_mfa_code]
    skip_before_action :verify_authenticity_token

    before_action :authenticate_api_user!, only: [:me, :logout, :regenerate_api_key]

    def register
      # Validate required fields
      unless params[:email].present? && params[:password].present?
        render json: { message: "Email and password are required" }, status: :unprocessable_entity
        return
      end

      # Check if email already exists (Story 0.2 - generic message to prevent enumeration)
      if User.exists?(email: params[:email]&.downcase)
        render json: { message: "Unable to create account. Please check your information and try again." }, status: :unprocessable_entity
        return
      end

      # Parse name
      full_name = params[:name].to_s.strip
      name_parts = full_name.split(/\s+/)
      first_name = name_parts.first.presence || "User"
      last_name = name_parts.length >= 2 ? name_parts[1..].join(" ") : ""

      # Create entity for the user
      business_name = params[:business_name].presence || "#{first_name} #{last_name} Business".strip
      entity = create_entity_for_registration(business_name)

      unless entity
        render json: { message: "Failed to create account. Please try again." }, status: :unprocessable_entity
        return
      end

      # Create user (Story 0.4 - API key generated by User model automatically)
      user = User.new(
        email: params[:email].downcase,
        password: params[:password],
        password_confirmation: params[:password],
        first_name: first_name,
        last_name: last_name,
        entity_id: entity.id
      )

      if user.save
        # Generate refresh token for token renewal (Story 0.4)
        user.generate_refresh_token!

        # Create EntityUser association
        EntityUser.create!(
          entity_id: entity.id,
          user: user,
          role: "owner"
        )

        Rails.logger.info "✅ Mobile registration: #{user.email} with entity #{entity.id}"

        render json: {
          user: {
            id: user.id,
            email: user.email,
            first_name: user.first_name,
            last_name: user.last_name,
            name: "#{user.first_name} #{user.last_name}".strip,
            entity_id: user.entity_id,
            entity_name: entity.name,
            role: "owner",
            mfa_enabled: user.otp_required_for_login
          },
          api_key: user.api_key,
          api_key_expires_at: user.api_key_expires_at,
          refresh_token: user.refresh_token,
          refresh_token_expires_at: user.refresh_token_expires_at,
          token: user.api_key
        }, status: :created
      else
        # Clean up entity if user creation failed
        entity.destroy
        # Generic message for all registration failures (Story 0.2)
        # Do NOT reveal specific validation details (e.g. password requirements)
        # to prevent information leakage
        render json: { message: "Unable to create account. Please check your information and try again." }, status: :unprocessable_entity
      end
    end

    def logout
      # Clear the cached user
      Rails.cache.delete("api_user:#{@current_user.api_key}")

      # Invalidate API key and refresh token (Story 0.4)
      @current_user.update(
        api_key: nil,
        api_key_expires_at: nil,
        refresh_token: nil,
        refresh_token_expires_at: nil
      )

      render json: { message: "Logged out successfully" }, status: :ok
    end

    def login
      user = User.find_by(email: params[:email]&.downcase)

      # Check account lockout BEFORE password verification (Story 0.1)
      if user&.account_locked?
        return render json: {
          message: 'Account temporarily locked due to multiple failed login attempts. Please try again in 30 minutes.'
        }, status: :locked
      end

      # Verify password
      if user&.valid_password?(params[:password])
        # Reset failed login attempts on successful login (Story 0.1)
        user.reset_failed_login!

        # MFA is not required for mobile API logins. The API key is device-bound
        # and mobile devices provide their own biometric security (Face ID/Touch ID).
        # Web users go through Devise which has its own MFA flow.
        render_login_success(user)
      else
        # Increment failed attempts (Story 0.1)
        user&.increment_failed_login!

        # Generic error message (Story 0.2 - prevents user enumeration)
        render json: { message: "Invalid email or password" }, status: :unauthorized
      end
    end

    # POST /api/auth/login-device
    # Login using a trusted device token (Face ID/biometric bypass)
    # This allows users to sign in without password if they have a trusted device
    def login_with_device_token
      email = params[:email]&.downcase
      device_token = params[:device_token]

      unless email.present? && device_token.present?
        render json: { message: "Email and device token are required" }, status: :unprocessable_entity
        return
      end

      user = User.find_by(email: email)

      # Check account lockout BEFORE device token validation (Story 0.1)
      # Prevents bypassing lockout via device tokens
      if user&.account_locked?
        return render json: {
          message: 'Account temporarily locked due to multiple failed login attempts. Please try again in 30 minutes.'
        }, status: :locked
      end

      # Find and validate the trusted device token
      # Use consistent error message to prevent user enumeration
      trusted_device = user&.trusted_devices&.active&.find_by(token: device_token)
      unless trusted_device
        render json: { message: "Invalid credentials" }, status: :unauthorized
        return
      end

      # Device token is valid - grant access without password/MFA
      trusted_device.touch_last_used!

      # SECURITY: Rotate device token on each use (prevents token replay attacks)
      new_device_token = SecureRandom.hex(32)
      trusted_device.update!(token: new_device_token)
      Rails.logger.info "🔐 Device token rotated for user #{user.email}"

      # Generate API key if not present
      if user.api_key.blank?
        user.update(api_key: SecureRandom.hex(32))
      end

      render json: {
        user: {
          id: user.id,
          email: user.email,
          first_name: user.first_name,
          last_name: user.last_name,
          name: "#{user.first_name} #{user.last_name}".strip,
          entity_id: user.entity_id,
          entity_name: user.entity&.name || 'My Business',
          role: user.role,
          mfa_enabled: user.otp_required_for_login
        },
        api_key: user.api_key,
        token: user.api_key,
        trusted_device_used: true,
        new_device_token: new_device_token  # Client must store this for next login
      }, status: :ok
    end

    def verify_mfa
      mfa_session_token = params[:mfa_session_token]
      code = params[:code]&.gsub(/\s/, "")

      unless mfa_session_token.present? && code.present?
        render json: { message: "MFA session token and code are required" }, status: :unprocessable_entity
        return
      end

      # Retrieve user ID from cache
      user_id = Rails.cache.read("mfa_session:#{mfa_session_token}")
      unless user_id
        render json: { message: "MFA session expired. Please login again." }, status: :unauthorized
        return
      end

      user = User.find_by(id: user_id)
      unless user
        render json: { message: "User not found" }, status: :unauthorized
        return
      end

      # Check if account is locked
      if user.otp_locked?
        render json: { message: "Too many failed attempts. Please try again later." }, status: :too_many_requests
        return
      end

      # Verify the OTP code (supports TOTP, email, and backup codes)
      # Allow bypass code in development mode for mobile app testing
      dev_bypass = Rails.env.development? && code == "000000"
      delivery_method = user.otp_delivery_method.presence || (user.otp_email_enabled? ? "email" : "totp")
      if dev_bypass || user.verify_otp(code, method: delivery_method)
        # Delete the MFA session token
        Rails.cache.delete("mfa_session:#{mfa_session_token}")

        # Generate API key if not present
        if user.api_key.blank?
          user.update(api_key: SecureRandom.hex(32))
        end

        render json: {
          user: {
            id: user.id,
            email: user.email,
            first_name: user.first_name,
            last_name: user.last_name,
            name: "#{user.first_name} #{user.last_name}".strip,
            entity_id: user.entity_id,
            entity_name: user.entity&.name || 'My Business',
            role: user.role,
            mfa_enabled: user.otp_required_for_login
          },
          api_key: user.api_key,
          token: user.api_key
        }, status: :ok
      else
        remaining = User::OTP_MAX_FAILED_ATTEMPTS - user.otp_failed_attempts
        render json: {
          message: "Invalid verification code",
          remaining_attempts: remaining > 0 ? remaining : 0
        }, status: :unauthorized
      end
    end

    def me
      render json: {
        user: {
          id: @current_user.id,
          email: @current_user.email,
          first_name: @current_user.first_name,
          last_name: @current_user.last_name,
          name: "#{@current_user.first_name} #{@current_user.last_name}".strip,
          entity_id: @current_user.entity_id,
          entity_name: @current_user.entity&.name || 'My Business',
          role: @current_user.role,
          mfa_enabled: @current_user.otp_required_for_login
        }
      }, status: :ok
    end

    # POST /api/auth/refresh
    # Use refresh token to get a new API key (Story 0.4)
    def refresh_token
      refresh_token_param = params[:refresh_token]

      unless refresh_token_param.present?
        return render json: { message: 'Refresh token required' }, status: :bad_request
      end

      # Find user with this refresh token
      user = User.find_by(refresh_token: refresh_token_param)

      unless user&.refresh_token_valid?(refresh_token_param)
        return render json: { message: 'Invalid or expired refresh token' }, status: :unauthorized
      end

      # Generate new API key and refresh token
      user.generate_api_key!
      user.generate_refresh_token!

      render json: {
        api_key: user.api_key,
        api_key_expires_at: user.api_key_expires_at,
        refresh_token: user.refresh_token,
        refresh_token_expires_at: user.refresh_token_expires_at
      }, status: :ok
    end

    # POST /api/auth/resend-mfa
    # Resend email OTP code for users with email-based MFA
    def resend_mfa_code
      mfa_session_token = params[:mfa_session_token]

      unless mfa_session_token.present?
        return render json: { message: "MFA session token is required" }, status: :unprocessable_entity
      end

      user_id = Rails.cache.read("mfa_session:#{mfa_session_token}")
      unless user_id
        return render json: { message: "MFA session expired. Please login again." }, status: :unauthorized
      end

      user = User.find_by(id: user_id)
      unless user
        return render json: { message: "User not found" }, status: :unauthorized
      end

      delivery_method = user.otp_delivery_method.presence || (user.otp_email_enabled? ? "email" : "totp")
      if delivery_method == "email"
        user.send_email_otp!
        render json: { message: "Verification code sent to your email" }, status: :ok
      else
        render json: { message: "TOTP codes are generated by your authenticator app" }, status: :ok
      end
    end

    def regenerate_api_key
      new_key = SecureRandom.hex(32)

      # Clear old cache
      Rails.cache.delete("api_user:#{@current_user.api_key}")

      if @current_user.update(api_key: new_key)
        render json: {
          api_key: new_key,
          message: "API key regenerated successfully"
        }, status: :ok
      else
        render json: { message: "Failed to regenerate API key" }, status: :unprocessable_entity
      end
    end

    private

    def authenticate_api_user!
      token = request.headers["Authorization"]&.gsub(/^Bearer /, "")

      unless token.present?
        render json: { message: "Authorization token required" }, status: :unauthorized
        return
      end

      # Cache only the user_id to avoid ActiveRecord association serialization issues
      # Full User object caching breaks associations like .entity
      user_id = Rails.cache.fetch("api_user_id:#{token}", expires_in: 5.minutes) do
        User.where(api_key: token).pick(:id)
      end

      @current_user = User.includes(:entity).find_by(id: user_id) if user_id

      unless @current_user
        render json: { message: "Invalid token" }, status: :unauthorized
        return
      end

      # Check API key expiration (Story 0.4)
      if @current_user.api_key_expired?
        render json: {
          message: "Authentication token has expired. Please refresh your token.",
          expired: true
        }, status: :unauthorized
        return
      end

      # Update last used timestamp (throttled to reduce DB writes - Story 0.4)
      if should_touch_api_key?
        TouchApiKeyJob.perform_later(@current_user.id) rescue @current_user.touch_api_key!
      end
    end

    def should_touch_api_key?
      # Only update every 5 minutes to reduce DB writes
      @current_user.api_key_last_used_at.nil? ||
        @current_user.api_key_last_used_at < 5.minutes.ago
    end

    def render_login_success(user, trusted_device: false)
      # Generate API key and refresh token (Story 0.4)
      user.generate_api_key!
      user.generate_refresh_token!

      render json: {
        user: {
          id: user.id,
          email: user.email,
          first_name: user.first_name,
          last_name: user.last_name,
          name: "#{user.first_name} #{user.last_name}".strip,
          entity_id: user.entity_id,
          entity_name: user.entity&.name || 'My Business',
          role: user.role,
          mfa_enabled: user.otp_required_for_login
        },
        api_key: user.api_key,
        api_key_expires_at: user.api_key_expires_at,
        token: user.api_key,  # Backward compatibility
        refresh_token: user.refresh_token,
        refresh_token_expires_at: user.refresh_token_expires_at,
        trusted_device_used: trusted_device
      }, status: :ok
    end

    def create_entity_for_registration(business_name)
      # Generate unique subdomain
      base_subdomain = business_name.parameterize
      subdomain = base_subdomain
      counter = 1

      while Entity.where(subdomain: subdomain).exists?
        subdomain = "#{base_subdomain}-#{counter}"
        counter += 1
      end

      Entity.create!(
        name: business_name,
        subdomain: subdomain,
        status: "active"
      )
    rescue => e
      Rails.logger.error "❌ Failed to create entity for registration: #{e.message}"
      nil
    end
  end
end
