#!/bin/bash

echo "❌ The Homebrew pgvector is built for PostgreSQL 17/18, not PostgreSQL 14"
echo ""
echo "You have several options:"
echo ""
echo "1. Use Podman PostgreSQL (RECOMMENDED):"
echo "   podman compose up -d db"
echo "   Then update your database.yml to use:"
echo "   host: localhost"
echo "   port: 5432"
echo "   username: postgres"
echo "   password: 123password"
echo ""
echo "2. Upgrade to PostgreSQL 17:"
echo "   brew install postgresql@17"
echo "   brew services stop postgresql@14"
echo "   brew services start postgresql@17"
echo "   # Then migrate your data"
echo ""
echo "3. Build pgvector from source for PostgreSQL 14:"
echo "   git clone https://github.com/pgvector/pgvector.git"
echo "   cd pgvector"
echo "   export PG_CONFIG=/opt/homebrew/opt/postgresql@14/bin/pg_config"
echo "   make"
echo "   sudo make install"
