#!/usr/bin/env ruby
# Script to generate a new RAG tool for Scout AI
#
# Usage:
#   docker compose exec web ruby .claude/skills/developing-rag-system/scripts/generate_rag_tool.rb <tool_name>
#
# Example:
#   docker compose exec web ruby .claude/skills/developing-rag-system/scripts/generate_rag_tool.rb search_brand_guidelines

require 'fileutils'

def generate_rag_tool(tool_name)
  # Convert to proper class name
  class_name = tool_name.camelize
  file_name = "#{tool_name}_tool.rb"
  file_path = Rails.root.join('app', 'services', 'tools', file_name)

  # Check if file exists
  if File.exist?(file_path)
    puts "❌ Error: Tool already exists at #{file_path}"
    exit 1
  end

  # Generate tool content
  tool_content = <<~RUBY
    # frozen_string_literal: true

    # #{class_name}Tool - Auto-generated RAG tool
    #
    # This tool queries the RAG system with entity scoping.
    # Modify the description, parameters, and execute method to fit your use case.
    #
    # Generated by: .claude/skills/developing-rag-system/scripts/generate_rag_tool.rb
    # Date: #{Time.current.strftime('%Y-%m-%d %H:%M:%S')}

    module Tools
      class #{class_name}Tool < BaseTool
        def self.definition
          {
            name: '#{tool_name}',
            description: 'Query the RAG system for relevant information (CUSTOMIZE THIS)',
            parameters: {
              type: 'object',
              properties: {
                query: {
                  type: 'string',
                  description: 'The search query to find relevant information'
                },
                store_name: {
                  type: 'string',
                  description: 'Optional: Specific RAG store name to search'
                },
                top_k: {
                  type: 'integer',
                  description: 'Number of results to return (default: 5)',
                  minimum: 1,
                  maximum: 20
                }
              },
              required: ['query']
            }
          }
        end

        def execute(args)
          query = args['query']
          store_name = args['store_name']
          top_k = args['top_k'] || 5

          # Get accessible RAG stores
          stores = RagStore.accessible_by(@entity)
                           .where(store_type: 'entity', status: 'active')

          # Filter by store name if specified
          stores = stores.where(name: store_name) if store_name.present?

          if stores.empty?
            return error_response(
              message: store_name.present? ?
                "RAG store '#{store_name}' not found" :
                "No RAG stores found for this entity"
            )
          end

          # Query all matching stores
          rag_service = RagStoreService.new
          results = stores.map do |store|
            rag_service.query_rag_store(
              store.id,
              query,
              current_entity: @entity,
              top_k: top_k
            )
          end

          # Combine and sort results by relevance
          all_chunks = results.flat_map { |r| r[:chunks] }
                              .sort_by { |c| -c[:score] }
                              .first(top_k)

          if all_chunks.empty?
            return success_response(
              message: "No relevant information found for query: '#{query}'",
              data: { query: query, results: [] }
            )
          end

          # Format results
          formatted_results = all_chunks.map do |chunk|
            {
              content: chunk[:content],
              score: (chunk[:score] * 100).round(1),
              source: chunk[:metadata][:source],
              metadata: chunk[:metadata].except(:source)
            }
          end

          success_response(
            message: "Found #{all_chunks.size} relevant result(s)",
            data: {
              query: query,
              result_count: all_chunks.size,
              results: formatted_results
            }
          )
        rescue => e
          error_response(
            message: "Error querying RAG system: #{e.message}",
            data: { error: e.class.name }
          )
        end
      end
    end
  RUBY

  # Write file
  File.write(file_path, tool_content)

  # Generate test file
  test_file_path = Rails.root.join('test', 'services', 'tools', "#{tool_name}_tool_test.rb")
  test_content = <<~RUBY
    # frozen_string_literal: true

    require 'test_helper'

    module Tools
      class #{class_name}ToolTest < ActiveSupport::TestCase
        setup do
          @entity = entities(:one)
          @user = users(:admin)
          @tool = #{class_name}Tool.new(
            user: @user,
            entity: @entity,
            workflow_execution: nil
          )

          # Create test RAG store
          @rag_store = RagStore.create!(
            name: 'Test Store',
            app_name: 'Test',
            store_type: 'entity',
            entity: @entity,
            user: @user,
            pinecone_index: 'test-index',
            pinecone_namespace: 'test-namespace',
            status: 'active'
          )
        end

        test "definition includes required fields" do
          definition = #{class_name}Tool.definition

          assert_equal '#{tool_name}', definition[:name]
          assert_includes definition[:description], 'RAG'
          assert_equal 'object', definition[:parameters][:type]
          assert_includes definition[:parameters][:required], 'query'
        end

        test "executes with valid query" do
          # Stub RAG service
          RagStoreService.any_instance.stubs(:query_rag_store).returns({
            chunks: [
              { content: 'Test content', score: 0.95, metadata: { source: 'test.txt' } }
            ]
          })

          result = @tool.execute({ 'query' => 'test query' })

          assert result[:success]
          assert_includes result[:message], 'Found'
          assert_equal 1, result[:data][:result_count]
        end

        test "returns error when no RAG stores exist" do
          @rag_store.destroy

          result = @tool.execute({ 'query' => 'test query' })

          assert_not result[:success]
          assert_includes result[:message], 'No RAG stores found'
        end

        test "filters by store name when specified" do
          RagStoreService.any_instance.stubs(:query_rag_store).returns({ chunks: [] })

          result = @tool.execute({
            'query' => 'test',
            'store_name' => 'Test Store'
          })

          assert result[:success]  # Should succeed even with no results
        end

        test "respects top_k parameter" do
          chunks = 10.times.map do |i|
            { content: "Chunk \#{i}", score: 0.9 - (i * 0.05), metadata: { source: 'test.txt' } }
          end

          RagStoreService.any_instance.stubs(:query_rag_store).returns({ chunks: chunks })

          result = @tool.execute({ 'query' => 'test', 'top_k' => 3 })

          assert result[:success]
          assert_equal 3, result[:data][:results].size
        end

        test "handles RAG service errors gracefully" do
          RagStoreService.any_instance.stubs(:query_rag_store).raises(StandardError.new('Connection failed'))

          result = @tool.execute({ 'query' => 'test' })

          assert_not result[:success]
          assert_includes result[:message], 'Error querying RAG system'
        end

        test "enforces entity scoping" do
          other_entity = entities(:two)
          other_store = RagStore.create!(
            name: 'Other Store',
            app_name: 'Test',
            store_type: 'entity',
            entity: other_entity,
            user: users(:other),
            pinecone_index: 'test-index',
            pinecone_namespace: 'other-namespace',
            status: 'active'
          )

          RagStoreService.any_instance.stubs(:query_rag_store).returns({ chunks: [] })

          result = @tool.execute({ 'query' => 'test' })

          # Should only query @rag_store, not other_store
          assert result[:success]
          # Verify only one store was queried (the entity's store)
        end
      end
    end
  RUBY

  File.write(test_file_path, test_content)

  # Success output
  puts "✅ RAG Tool Generated Successfully!"
  puts ""
  puts "📦 Tool File:  #{file_path}"
  puts "🧪 Test File:  #{test_file_path}"
  puts ""
  puts "Next Steps:"
  puts "  1. Customize the tool description and parameters in #{file_name}"
  puts "  2. Modify the execute() method for your specific use case"
  puts "  3. Run tests: docker compose exec web rails test #{test_file_path}"
  puts "  4. The tool will auto-discover via ToolCatalog - no registration needed!"
  puts ""
  puts "Usage in Scout:"
  puts "  User: \"[Your query that would trigger this tool]\""
  puts "  Scout: *Uses #{tool_name} tool → Returns results*"
  puts ""
end

# Main execution
if ARGV.empty?
  puts "Usage: ruby generate_rag_tool.rb <tool_name>"
  puts ""
  puts "Example:"
  puts "  ruby generate_rag_tool.rb search_brand_guidelines"
  exit 1
end

tool_name = ARGV[0]

# Validate tool name
unless tool_name.match?(/^[a-z][a-z0-9_]*$/)
  puts "❌ Error: Tool name must be lowercase with underscores (e.g., search_brand_guidelines)"
  exit 1
end

generate_rag_tool(tool_name)
