import 'package:amos_mobile/models/user.dart';
import 'package:amos_mobile/services/api_client.dart';
import 'package:amos_mobile/services/storage_service.dart';

class AuthService {
  final ApiClient _api = ApiClient();
  final StorageService _storage = StorageService.instance;

  static const _tokenKey = 'auth_token';
  static const _userKey = 'user_data';

  Future<LoginResult> login(String email, String password) async {
    final response = await _api.post('/api/auth/login', data: {
      'email': email,
      'password': password,
    });

    // Check if MFA is required
    if (response['mfa_required'] == true) {
      return LoginResult(
        mfaRequired: true,
        mfaSessionToken: response['mfa_session_token'] as String,
      );
    }

    // Normal login without MFA
    final user = User.fromJson(response['user']);
    final token = (response['api_key'] ?? response['token']) as String;

    // Set token directly on ApiClient (reliable, bypasses storage issues)
    ApiClient.instance.setAuthToken(token);

    // Also store in secure storage for persistence
    await _storage.write(_tokenKey, token);
    await _storage.write(_userKey, user.id);

    return LoginResult(
      authResult: AuthResult(user: user, token: token),
    );
  }

  Future<AuthResult> register({
    required String email,
    required String password,
    required String name,
    String? businessName,
  }) async {
    final response = await _api.post('/api/auth/register', data: {
      'email': email,
      'password': password,
      'name': name,
      if (businessName != null && businessName.isNotEmpty) 'business_name': businessName,
    });

    final user = User.fromJson(response['user']);
    final token = (response['api_key'] ?? response['token']) as String;

    // Set token directly on ApiClient
    ApiClient.instance.setAuthToken(token);

    // Also store in secure storage for persistence
    await _storage.write(_tokenKey, token);
    await _storage.write(_userKey, user.id);

    return AuthResult(user: user, token: token);
  }

  Future<AuthResult> verifyMFACode({
    required String mfaSessionToken,
    required String code,
    bool useBackupCode = false,
  }) async {
    final response = await _api.post('/api/auth/verify-mfa', data: {
      'mfa_session_token': mfaSessionToken,
      'code': code,
    });

    final user = User.fromJson(response['user']);
    final token = (response['api_key'] ?? response['token']) as String;

    // Set token directly on ApiClient
    ApiClient.instance.setAuthToken(token);

    await _storage.write(_tokenKey, token);
    await _storage.write(_userKey, user.id);

    return AuthResult(user: user, token: token);
  }

  Future<void> resendMFACode(String mfaSessionToken) async {
    // TOTP codes are generated by the authenticator app, no resend needed
    // This is a no-op for TOTP but kept for interface compatibility
  }

  Future<void> logout() async {
    try {
      await _api.post('/api/auth/logout');
    } finally {
      // Clear token from ApiClient and storage
      ApiClient.instance.clearAuthToken();
      await _storage.delete(_userKey);
    }
  }

  Future<AuthResult?> checkAuth() async {
    final token = await _storage.read(_tokenKey);
    if (token == null) return null;

    // Set token on ApiClient for subsequent requests
    ApiClient.instance.setAuthToken(token);

    try {
      final response = await _api.get('/api/auth/me');
      final user = User.fromJson(response['user']);
      return AuthResult(user: user, token: token);
    } catch (e) {
      ApiClient.instance.clearAuthToken();
      await _storage.delete(_userKey);
      return null;
    }
  }

  Future<void> forgotPassword(String email) async {
    await _api.post('/api/auth/forgot-password', data: {'email': email});
  }

  /// Login with a trusted device token (bypasses MFA)
  /// This is used when the user has previously trusted this device and
  /// is using Face ID/biometrics to sign in.
  Future<LoginResult> loginWithDeviceToken({
    required String email,
    required String deviceToken,
  }) async {
    final response = await _api.post('/api/auth/login-device', data: {
      'email': email,
      'device_token': deviceToken,
    });

    // Login successful with device token
    final user = User.fromJson(response['user']);
    final token = (response['api_key'] ?? response['token']) as String;

    // Set token directly on ApiClient
    ApiClient.instance.setAuthToken(token);

    // Also store in secure storage for persistence
    await _storage.write(_tokenKey, token);
    await _storage.write(_userKey, user.id);

    return LoginResult(
      authResult: AuthResult(user: user, token: token),
    );
  }
}
