require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Configure subdomain handling for localhost
  # This tells Rails to treat "localhost" as a single TLD (like ".com")
  # So "app.localhost" will have subdomain="app" instead of subdomain=""
  config.action_dispatch.tld_length = 0

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  # Use Redis for development to share cache between processes (web and worker)
  config.cache_store = :redis_cache_store, { 
    url: ENV["REDIS_URL"] || "redis://localhost:6379/0",
    namespace: "amos_dev_cache"
  }

  # Store uploaded files - use Amazon S3 if AWS credentials are available, otherwise local
  config.active_storage.service = ENV['AWS_ACCESS_KEY_ID'].present? ? :amazon : :local

  # Set Active Storage URL host in development
  # S3 presigned URLs have a max of 7 days
  config.active_storage.service_urls_expire_in = 7.days
  Rails.application.routes.default_url_options[:host] = "localhost"
  Rails.application.routes.default_url_options[:port] = 3000

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = true

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Devise mailer configuration
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Use SES in development if explicitly requested via USE_SES_IN_DEV=true
  if ENV["USE_SES_IN_DEV"] == "true"
    config.action_mailer.delivery_method = :aws_sdk
    config.action_mailer.perform_deliveries = true
  else
    # Use letter_opener_web for Docker (provides web UI at /letter_opener)
    config.action_mailer.delivery_method = :letter_opener_web
    config.action_mailer.perform_deliveries = true
  end

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  # Disabled for cleaner console output in development
  config.active_record.verbose_query_logs = false

  # Append comments with runtime information tags to SQL queries in logs.
  # Disabled for cleaner console output in development
  config.active_record.query_log_tags_enabled = false

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Set log level to reduce debug information
  # config.log_level = :info

  # Disable debug request logging
  # config.middleware.delete ActionDispatch::DebugExceptions

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  config.action_cable.disable_request_forgery_protection = true
  config.action_cable.allowed_request_origins = [/http:\/\/*/, /https:\/\/*/, /file:\/\/*/, /ws:\/\/*/, /wss:\/\/*/, nil]

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Allow accessing the application via custom domains/subdomains in development
  config.hosts << ".localhost"
  config.hosts << "localhost"
  config.hosts << "app.localhost"
  config.hosts << "app.app.localhost"
  config.hosts << ".lvh.me"
  config.hosts << "lvh.me"
  config.hosts << "app.lvh.me"

  # Allow some additional localhost variations that might be used during development
  config.hosts << "127.0.0.1"
  config.hosts << "app.127.0.0.1"
  config.hosts << "app.app.127.0.0.1"

  # Allow testing with a fake domain
  config.hosts << ".yourdomain.test"
  config.hosts << "yourdomain.test"
  config.hosts << "app.yourdomain.test"
  config.hosts << "app.app.yourdomain.test"

  # Allow nuvola development environment
  config.hosts << "nuvola.default.localhost"
  config.hosts << ".nuvola.default.localhost"
  config.hosts << "default.localhost"
  config.hosts << ".default.localhost"
  
  # Container hosts (Podman and Docker)
  config.hosts << "host.docker.internal"
  config.hosts << "host.containers.internal"
  config.hosts << /.*\.docker\.internal/
  config.hosts << /.*\.containers\.internal/

  # Allow container-to-container communication
  config.hosts << "web"

  # Disable CSRF protection in development to match production behavior
  # This prevents CSRF token authenticity errors with complex subdomain setups
  config.action_controller.allow_forgery_protection = false
end
