class LandingPagesController < ApplicationController
  before_action :authenticate_user!
  layout 'customer_admin', except: [:public_view, :preview, :no_header_preview]
  before_action :set_landing_page, only: [ :show, :edit, :update, :destroy, :publish, :unpublish, :preview, :generate_image, :generate_content, :chat, :apply_change, :no_header_preview, :get_chat_messages, :clarify, :answer_clarification ]

  # Skip authentication for public landing page views
  skip_before_action :authenticate_user!, only: [ :public_view ]

  def index
    @landing_pages = current_user.landing_pages.where(entity_id: current_entity.id).order(created_at: :desc)
    
    # Check if user recently created a landing page (within last 5 minutes)
    # This helps users who missed the streaming response know their page was created
    recent_landing_page = @landing_pages.where(created_at: 5.minutes.ago..Time.current).first
    if recent_landing_page
      flash.now[:success] = "🎉 Your landing page '#{recent_landing_page.title}' was created successfully! You can edit it below."
    end
  end

  def show
  end

  def new
    @landing_page = current_user.landing_pages.new(entity_id: current_entity.id)

    # Get business profile for context in the wizard
    @business_profile = current_entity.business_profiles.first || current_user.business_profile

    # Pre-populate campaign info if provided
    if params[:campaign_id].present?
      @campaign = current_user.campaigns.where(entity_id: current_entity.id).find_by(id: params[:campaign_id])
      if @campaign
        @landing_page.campaign_id = @campaign.id
        @landing_page.title = "Landing page for #{@campaign.name}"
      end
    end
  end

  def create
    @landing_page = current_user.landing_pages.new(landing_page_params)
    @landing_page.entity_id = current_entity.id

    # Get business profile for context
    @business_profile = current_entity.business_profiles.first || current_user.business_profile

    # Skip validation if title/slug will be generated by AI
    if @landing_page.title.blank?
      @landing_page.skip_title_validation = true
    end
    if @landing_page.slug.blank?
      @landing_page.skip_slug_validation = true
    end

    if @landing_page.save
      # Generate title and slug using AI if not provided
      if @landing_page.title.blank?
        generate_title_and_slug
        @landing_page.skip_title_validation = false
        @landing_page.skip_slug_validation = false
        @landing_page.save!
      end

      case params[:action]
      when "generate_with_ai"
        # Generate clarification questions first, then determine next step
        GenerateLandingPageClarificationJob.perform_now(
          @landing_page.id,
          @landing_page.description,
          current_entity.id,
          @business_profile&.id
        )

        # Reload to get the clarification questions
        @landing_page.reload

        if @landing_page.clarification_questions.present? && @landing_page.clarification_questions.any?
          # Show clarification form
          redirect_to clarify_landing_page_path(@landing_page), notice: "Just a few quick questions to create the perfect landing page."
        else
          # No clarification needed, generate directly
          GenerateFullLandingPageJob.perform_now(
            @landing_page.id,
            @landing_page.description,
            {},
            current_entity.id,
            @business_profile&.id
          )
          redirect_to chat_landing_page_path(@landing_page), notice: "Your landing page has been created!"
        end
      else
        # Default behavior
        redirect_to chat_landing_page_path(@landing_page), notice: "Landing page was successfully created."
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # Show clarification questions
  def clarify
    @business_profile = current_entity.business_profiles.first || current_user.business_profile
    # Questions should already be generated by the create action
  end

  # Handle clarification responses
  def answer_clarification
    clarification_answers = params[:clarification_answers]

    if clarification_answers.present?
      # Store answers and generate the landing page immediately
      @landing_page.update(clarification_answers: clarification_answers)

      # Generate the full landing page with AI
      GenerateFullLandingPageJob.perform_now(
        @landing_page.id,
        @landing_page.description,
        clarification_answers,
        current_entity.id,
        @business_profile&.id
      )

      redirect_to chat_landing_page_path(@landing_page), notice: "Your landing page has been created!"
    else
      redirect_to clarify_landing_page_path(@landing_page), alert: "Please answer the clarification questions."
    end
  end

  # Chat interface for managing the landing page
  def chat
    @business_profile = current_entity.business_profiles.first || current_user.business_profile
  end

  def edit
    # Get business profile for context in AI generation
    @business_profile = current_entity.business_profiles.first || current_user.business_profile
  end

  def inline_edit
    @landing_page = current_entity.landing_pages.find_by!(slug: params[:id])
  end

  def update
    if @landing_page.update(landing_page_params)
      respond_to do |format|
        format.html { redirect_to landing_page_path(@landing_page), notice: "Landing page was successfully updated." }
        format.json { render json: { success: true, message: "Landing page was successfully updated." } }
      end
    else
      respond_to do |format|
        format.html { render :chat, status: :unprocessable_entity }
        format.json { render json: { success: false, error: @landing_page.errors.full_messages.join(", ") }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @landing_page.destroy
    redirect_to landing_pages_path, notice: "Landing page was successfully deleted."
  end

  def publish
    if @landing_page.update(published: true, status: "published")
      redirect_to landing_pages_path, notice: "Landing page has been published."
    else
      redirect_to edit_landing_page_path(@landing_page), alert: "Unable to publish landing page."
    end
  end

  def unpublish
    if @landing_page.update(published: false, status: "draft")
      redirect_to landing_pages_path, notice: "Landing page has been unpublished."
    else
      redirect_to edit_landing_page_path(@landing_page), alert: "Unable to unpublish landing page."
    end
  end

  def preview
    respond_to do |format|
      format.html {
        if @landing_page.html_content.present?
          # Remove all editing-related attributes and classes for clean preview
          clean_html = strip_editing_attributes(@landing_page.html_content)
          render html: clean_html.html_safe
        else
          render plain: "No HTML content generated yet. Please generate the landing page first."
        end
      }
      format.json { render json: @landing_page.preview_data }
    end
  end

  def no_header_preview
    respond_to do |format|
      format.html { render layout: "landing_page_content_only", inline: "" }
    end
  end

  def generate_content
    # Prepare context for AI generation
    business_profile = current_entity.business_profiles.first || current_user.business_profile

    topic = params[:description]
    page_type = params[:page_type] || "lead_generation"

    # Use the new multi-agent system for content generation
    AgentGenerateLandingPageJob.perform_later(
      @landing_page.id,
      topic,
      current_entity.id,
      business_profile&.id,
      page_type
    )

    redirect_to edit_landing_page_path(@landing_page), notice: "Content generation has been started using our advanced AI agent system. This process may take a bit longer but will produce higher quality results."
  end

  # Generate images to replace placeholders like 1200x600 or placehold.co URLs
  def generate_images
    sizes_map = params[:sizes_map] || {}
    GenerateImagesForLandingPageJob.perform_later(@landing_page.id, sizes_map, user_id: current_user.id, entity_id: current_entity.id)
    redirect_to edit_landing_page_path(@landing_page), notice: "Image generation started. Refresh in a moment."
  end

  def generate_image
    description = params[:image_description]
    section = params[:section] || "hero"

    # Create the AI image generation job
    GenerateLandingPageImageJob.perform_later(
      @landing_page.id,
      description,
      section
    )

    redirect_to edit_landing_page_path(@landing_page), notice: "Image generation has been started. This may take a few moments."
  end

  def chat_preview
    # Get business profile for context in AI generation
    @business_profile = current_entity.business_profiles.first || current_user.business_profile

    respond_to do |format|
      format.html { render layout: "landing_page_chat" }
    end
  end

  def apply_change
    # Handle AI-requested changes to the full HTML content
    instruction = params[:instruction]

    # Get business profile for context
    business_profile = current_entity.business_profiles.first || current_user.business_profile

    # Create a job to apply the change to the HTML content
    ApplyHtmlLandingPageChangeJob.perform_later(
      @landing_page.id,
      instruction,
      current_entity.id,
      current_user.id,
      business_profile&.id
    )

    render json: {
      status: "processing",
      message: "Your request is being processed. The page will update shortly."
    }
  end

  def get_chat_messages
    @landing_page = current_user.landing_pages.where(entity_id: current_entity.id).find_by!(slug: params[:id])
    messages = @landing_page.landing_page_chat_messages.order(created_at: :asc)

    render json: {
      messages: messages.map do |msg|
        {
          id: msg.id,
          content: msg.content,
          role: msg.role,
          timestamp: msg.created_at.iso8601
        }
      end
    }
  end

  # Public-facing landing page view (no auth required)
  def public_view
    @landing_page = LandingPage.published.find_by!(slug: params[:slug])

    # Track the view
    track_landing_page_view

    # Render the complete HTML content directly (like preview method)
    if @landing_page.html_content.present?
      # Remove all editing-related attributes and classes for clean public view
      clean_html = strip_editing_attributes(@landing_page.html_content)
      render html: clean_html.html_safe
    else
      render plain: "This landing page is not yet available.", status: :not_found
    end
  rescue ActiveRecord::RecordNotFound
    render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
  end

  # Show version history
  def versions
    @versions = @landing_page.landing_page_versions.order(created_at: :desc)

    respond_to do |format|
      format.html
      format.json { render json: @versions }
    end
  end

  # Rollback to a specific version
  def rollback
    @version = @landing_page.landing_page_versions.find(params[:version_id])

    if @version.restore
      respond_to do |format|
        format.html { redirect_to edit_landing_page_path(@landing_page), notice: "Successfully rolled back to previous version." }
        format.json { render json: { status: "success", message: "Successfully rolled back to previous version." } }
      end
    else
      respond_to do |format|
        format.html { redirect_to edit_landing_page_path(@landing_page), alert: "Failed to rollback to previous version." }
        format.json { render json: { status: "error", message: "Failed to rollback to previous version." }, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_landing_page
    @landing_page = current_user.landing_pages.where(entity_id: current_entity.id).find_by!(slug: params[:id])
  end

  def strip_editing_attributes(html_content)
    # Remove all editing-related attributes and classes for clean preview
    clean_html = html_content.dup

    # Remove contenteditable attributes
    clean_html.gsub!(/\s*contenteditable\s*=\s*["']true["']/i, "")
    clean_html.gsub!(/\s*contenteditable\s*=\s*["']false["']/i, "")
    clean_html.gsub!(/\s*contenteditable/i, "")

    # Remove spellcheck attributes
    clean_html.gsub!(/\s*spellcheck\s*=\s*["']false["']/i, "")
    clean_html.gsub!(/\s*spellcheck\s*=\s*["']true["']/i, "")

    # Remove data-original-content attributes
    clean_html.gsub!(/\s*data-original-content\s*=\s*["'][^"']*["']/i, "")

    # Remove editing-related classes
    clean_html.gsub!(/\s*editable-text\s*/, " ")
    clean_html.gsub!(/\s*editable-image\s*/, " ")
    clean_html.gsub!(/\s*editable-element\s*/, " ")

    # FIX: Add 'animated' class to all 'animate-on-scroll' elements so they're visible
    # Without this, elements with animate-on-scroll have opacity:0 and stay invisible
    clean_html.gsub!(/class\s*=\s*["']([^"']*animate-on-scroll[^"']*)["']/) do |match|
      classes = $1
      if classes.include?('animated')
        match
      else
        "class=\"#{classes} animated\""
      end
    end

    # Clean up any double spaces left by class removal
    clean_html.gsub!(/\s+/, " ")
    clean_html.gsub!(/class\s*=\s*["']\s*["']/, "")

    clean_html
  end

  def generate_title_and_slug
    # Generate title using AI based on description
    description = @landing_page.description || "landing page"

    begin
      # Use ClaudeService with proper system and user message format
      system_prompt = "You are a marketing expert who creates compelling landing page titles."
      user_message = "Based on this landing page description, create a compelling 3-8 word title:

\"#{description}\"

Return only the title, nothing else. Make it clear, compelling, and action-oriented."

      response = ClaudeService.new.send_message(system_prompt, user_message)
      title = response.strip.gsub(/["""]/, "")

      # Fallback if AI response is too long or empty
      if title.blank? || title.length > 100
        title = description.split(".").first&.strip || "New Landing Page"
        title = title[0..50] if title.length > 50
      end

      @landing_page.title = title

      # Generate unique slug from title
      base_slug = title.parameterize
      base_slug = "landing-page" if base_slug.blank?

      # Ensure uniqueness
      slug = base_slug
      counter = 1
      while LandingPage.where(slug: slug).exists?
        slug = "#{base_slug}-#{counter}"
        counter += 1
      end

      @landing_page.slug = slug

      Rails.logger.info "Successfully generated title: '#{title}' and slug: '#{slug}'"

    rescue => e
      Rails.logger.error "Error generating title and slug: #{e.message}"
      Rails.logger.error e.backtrace.join("\n")

      # Fallback to simple title and slug
      @landing_page.title = "New Landing Page"
      base_slug = "landing-page-#{Time.current.to_i}"
      @landing_page.slug = base_slug
    end
  end

  def landing_page_params
    params.require(:landing_page).permit(
      :title,
      :slug,
      :description,
      :campaign_id,
      :html_content,
      :status,
      :published,
      :meta_description,
      :meta_keywords,
      :clarification_questions,
      :clarification_answers
    )
  end

  def track_landing_page_view
    # Implement view tracking logic here
    # Could record visitor info, referrer, etc.
  end

  def generate_initial_content
    # Build comprehensive context for AI generation
    context = {
      business_profile: @business_profile,
      design_preferences: {
        page_type: @landing_page.page_type,
        tone_preference: @landing_page.tone_preference,
        content_length: @landing_page.content_length,
        primary_color: @landing_page.primary_color,
        secondary_color: @landing_page.secondary_color,
        font_family: @landing_page.font_family
      },
      features: {
        include_testimonials: @landing_page.include_testimonials,
        include_features: @landing_page.include_features,
        include_faq: @landing_page.include_faq,
        include_pricing: @landing_page.include_pricing,
        include_about: @landing_page.include_about,
        include_contact: @landing_page.include_contact
      }
    }

    # Use the enhanced AI generation job with all context
    AgentGenerateLandingPageJob.perform_later(
      @landing_page.id,
      @landing_page.description,
      current_entity.id,
      @business_profile&.id,
      @landing_page.page_type,
      context
    )
  end
end
