class LandingPagesController < ApplicationController
  include Authorizable
  include LandingPageRendering
  before_action :authenticate_user!
  layout 'customer_admin', except: [:public_view, :preview, :no_header_preview]
  before_action :set_landing_page, only: [ :show, :edit, :update, :destroy, :publish, :unpublish, :preview, :generate_image, :generate_content, :chat, :apply_change, :no_header_preview, :get_chat_messages, :clarify, :answer_clarification, :versions, :rollback ]
  before_action :authorize_destroy!, only: [:destroy]

  # Skip authentication for public landing page views
  skip_before_action :authenticate_user!, only: [ :public_view ]

  def index
    @landing_pages = current_user.landing_pages.where(entity_id: current_entity.id).order(created_at: :desc)
    
    # Check if user recently created a landing page (within last 5 minutes)
    # This helps users who missed the streaming response know their page was created
    recent_landing_page = @landing_pages.where(created_at: 5.minutes.ago..Time.current).first
    if recent_landing_page
      flash.now[:success] = "🎉 Your landing page '#{recent_landing_page.title}' was created successfully! You can edit it below."
    end
  end

  def show
  end

  def new
    @landing_page = current_user.landing_pages.new(entity_id: current_entity.id)

    # Get business profile for context in the wizard
    @business_profile = current_entity.business_profiles.first || current_user.business_profile

    # Pre-populate campaign info if provided
    if params[:campaign_id].present?
      @campaign = current_user.campaigns.where(entity_id: current_entity.id).find_by(id: params[:campaign_id])
      if @campaign
        @landing_page.campaign_id = @campaign.id
        @landing_page.title = "Landing page for #{@campaign.name}"
      end
    end
  end

  def create
    @landing_page = current_user.landing_pages.new(landing_page_params)
    @landing_page.entity_id = current_entity.id

    # Get business profile for context
    @business_profile = current_entity.business_profiles.first || current_user.business_profile

    # Skip validation if title/slug will be generated by AI
    if @landing_page.title.blank?
      @landing_page.skip_title_validation = true
    end
    if @landing_page.slug.blank?
      @landing_page.skip_slug_validation = true
    end

    if @landing_page.save
      # Generate title and slug using AI if not provided
      if @landing_page.title.blank?
        generate_title_and_slug
        @landing_page.skip_title_validation = false
        @landing_page.skip_slug_validation = false
        @landing_page.save!
      end

      # Handle JSON requests from Design Panel
      respond_to do |format|
        format.json do
          # Apply template if specified
          if params.dig(:landing_page, :template_id).present?
            apply_template_to_landing_page(params[:landing_page][:template_id])
          end
          
          render json: {
            success: true,
            landing_page: {
              id: @landing_page.id,
              title: @landing_page.title,
              slug: @landing_page.slug,
              status: @landing_page.status
            },
            redirect_url: edit_landing_page_path(@landing_page)
          }
        end
        
        format.html do
          case params[:action]
          when "generate_with_ai"
            # Generate clarification questions first, then determine next step
            GenerateLandingPageClarificationJob.perform_now(
              @landing_page.id,
              @landing_page.description,
              current_entity.id,
              @business_profile&.id
            )

            # Reload to get the clarification questions
            @landing_page.reload

            if @landing_page.clarification_questions.present? && @landing_page.clarification_questions.any?
              # Show clarification form
              redirect_to clarify_landing_page_path(@landing_page), notice: "Just a few quick questions to create the perfect landing page."
            else
              # No clarification needed, generate directly
              GenerateFullLandingPageJob.perform_now(
                @landing_page.id,
                @landing_page.description,
                {},
                current_entity.id,
                @business_profile&.id
              )
              redirect_to chat_landing_page_path(@landing_page), notice: "Your landing page has been created!"
            end
          else
            # Default behavior
            redirect_to chat_landing_page_path(@landing_page), notice: "Landing page was successfully created."
          end
        end
      end
    else
      respond_to do |format|
        format.json { render json: { success: false, errors: @landing_page.errors.full_messages }, status: :unprocessable_entity }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # Show clarification questions
  def clarify
    @business_profile = current_entity.business_profiles.first || current_user.business_profile
    # Questions should already be generated by the create action
  end

  # Handle clarification responses
  def answer_clarification
    clarification_answers = params[:clarification_answers]

    if clarification_answers.present?
      # Store answers and generate the landing page immediately
      @landing_page.update(clarification_answers: clarification_answers)

      # Generate the full landing page with AI
      GenerateFullLandingPageJob.perform_now(
        @landing_page.id,
        @landing_page.description,
        clarification_answers,
        current_entity.id,
        @business_profile&.id
      )

      redirect_to chat_landing_page_path(@landing_page), notice: "Your landing page has been created!"
    else
      redirect_to clarify_landing_page_path(@landing_page), alert: "Please answer the clarification questions."
    end
  end

  # Chat interface for managing the landing page
  def chat
    @business_profile = current_entity.business_profiles.first || current_user.business_profile
  end

  def edit
    # Get business profile for context in AI generation
    @business_profile = current_entity.business_profiles.first || current_user.business_profile
  end

  def inline_edit
    @landing_page = current_entity.landing_pages.find_by!(slug: params[:id])
  end

  def update
    if @landing_page.update(landing_page_params)
      respond_to do |format|
        format.html { redirect_to landing_page_path(@landing_page), notice: "Landing page was successfully updated." }
        format.json { render json: { success: true, message: "Landing page was successfully updated." } }
      end
    else
      respond_to do |format|
        format.html { render :chat, status: :unprocessable_entity }
        format.json { render json: { success: false, error: @landing_page.errors.full_messages.join(", ") }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @landing_page.destroy
    redirect_to landing_pages_path, notice: "Landing page was successfully deleted."
  end

  def publish
    if @landing_page.update(status: "published")
      public_url = @landing_page.subdomain_url || @landing_page.full_url
      redirect_to landing_pages_path, notice: "Landing page published! Live at: #{public_url}"
    else
      redirect_to edit_landing_page_path(@landing_page), alert: "Unable to publish landing page."
    end
  end

  def unpublish
    if @landing_page.update(status: "draft")
      redirect_to landing_pages_path, notice: "Landing page has been unpublished."
    else
      redirect_to edit_landing_page_path(@landing_page), alert: "Unable to unpublish landing page."
    end
  end

  def preview
    respond_to do |format|
      format.html {
        if @landing_page.html_content.present?
          # Remove all editing-related attributes and classes for clean preview
          clean_html = strip_editing_attributes(@landing_page.html_content)
          # Ensure HTML structure is complete (fix truncated content)
          clean_html = ensure_html_structure(clean_html)
          # Sanitize forms to remove any action/method attributes
          clean_html = sanitize_form_attributes(clean_html)
          # Inject form handling script for AI-generated pages
          clean_html = inject_form_handling_script(clean_html, @landing_page.slug)
          # Inject page font if set
          clean_html = inject_page_font(clean_html, @landing_page.page_font)
          render html: clean_html.html_safe
        else
          render plain: "No HTML content generated yet. Please generate the landing page first."
        end
      }
      format.json { render json: @landing_page.preview_data }
    end
  end

  def no_header_preview
    respond_to do |format|
      format.html { render layout: "landing_page_content_only", inline: "" }
    end
  end

  def generate_content
    # Prepare context for AI generation
    business_profile = current_entity.business_profiles.first || current_user.business_profile

    topic = params[:description]
    page_type = params[:page_type] || "lead_generation"

    # Use the new multi-agent system for content generation
    AgentGenerateLandingPageJob.perform_later(
      @landing_page.id,
      topic,
      current_entity.id,
      business_profile&.id,
      page_type
    )

    redirect_to edit_landing_page_path(@landing_page), notice: "Content generation has been started using our advanced AI agent system. This process may take a bit longer but will produce higher quality results."
  end

  # Generate images to replace placeholders like 1200x600 or placehold.co URLs
  def generate_images
    sizes_map = params[:sizes_map] || {}
    GenerateImagesForLandingPageJob.perform_later(@landing_page.id, sizes_map, user_id: current_user.id, entity_id: current_entity.id)
    redirect_to edit_landing_page_path(@landing_page), notice: "Image generation started. Refresh in a moment."
  end

  def generate_image
    description = params[:image_description]
    section = params[:section] || "hero"

    # Create the AI image generation job
    GenerateLandingPageImageJob.perform_later(
      @landing_page.id,
      description,
      section
    )

    redirect_to edit_landing_page_path(@landing_page), notice: "Image generation has been started. This may take a few moments."
  end

  def chat_preview
    # Get business profile for context in AI generation
    @business_profile = current_entity.business_profiles.first || current_user.business_profile

    respond_to do |format|
      format.html { render layout: "landing_page_chat" }
    end
  end

  def apply_change
    # Handle AI-requested changes to the full HTML content
    instruction = params[:instruction]

    # Get business profile for context
    business_profile = current_entity.business_profiles.first || current_user.business_profile

    # Create a job to apply the change to the HTML content
    ApplyHtmlLandingPageChangeJob.perform_later(
      @landing_page.id,
      instruction,
      current_entity.id,
      current_user.id,
      business_profile&.id
    )

    render json: {
      status: "processing",
      message: "Your request is being processed. The page will update shortly."
    }
  end

  def get_chat_messages
    @landing_page = current_user.landing_pages.where(entity_id: current_entity.id).find_by!(slug: params[:id])
    messages = @landing_page.landing_page_chat_messages.order(created_at: :asc)

    render json: {
      messages: messages.map do |msg|
        {
          id: msg.id,
          content: msg.content,
          role: msg.role,
          timestamp: msg.created_at.iso8601
        }
      end
    }
  end

  # Public-facing landing page view (no auth required)
  def public_view
    @landing_page = LandingPage.published.find_by!(slug: params[:slug])

    # Track the view
    track_landing_page_view

    # Render the complete HTML content directly (like preview method)
    if @landing_page.html_content.present?
      # Remove all editing-related attributes and classes for clean public view
      clean_html = strip_editing_attributes(@landing_page.html_content)
      # Ensure HTML structure is complete (fix truncated content)
      clean_html = ensure_html_structure(clean_html)
      # Sanitize forms to remove any action/method attributes
      clean_html = sanitize_form_attributes(clean_html)
      # Inject form handling script for AI-generated pages
      clean_html = inject_form_handling_script(clean_html, @landing_page.slug)
      # Inject page font if set
      clean_html = inject_page_font(clean_html, @landing_page.page_font)
      render html: clean_html.html_safe
    else
      render plain: "This landing page is not yet available.", status: :not_found
    end
  rescue ActiveRecord::RecordNotFound
    render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
  end

  # Show version history
  def versions
    @versions = @landing_page.landing_page_versions.order(created_at: :desc)

    respond_to do |format|
      format.html
      format.json { render json: @versions }
    end
  end

  # Rollback to a specific version
  def rollback
    @version = @landing_page.landing_page_versions.find(params[:version_id])

    if @version.restore
      respond_to do |format|
        format.html { redirect_to edit_landing_page_path(@landing_page), notice: "Successfully rolled back to previous version." }
        format.json { render json: { status: "success", message: "Successfully rolled back to previous version." } }
      end
    else
      respond_to do |format|
        format.html { redirect_to edit_landing_page_path(@landing_page), alert: "Failed to rollback to previous version." }
        format.json { render json: { status: "error", message: "Failed to rollback to previous version." }, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_landing_page
    # Support lookup by both ID (numeric) and slug (string)
    if params[:id].to_s.match?(/\A\d+\z/)
      @landing_page = current_user.landing_pages.where(entity_id: current_entity.id).find(params[:id])
    else
      @landing_page = current_user.landing_pages.where(entity_id: current_entity.id).find_by!(slug: params[:id])
    end
  end

  def apply_template_to_landing_page(template_id)
    # Define template starter HTML based on template ID
    templates = {
      'lp_saas' => <<~HTML,
        <section class="hero-section" style="padding: 4rem 2rem; text-align: center; background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);">
          <h1 style="font-size: 3rem; font-weight: bold; margin-bottom: 1rem; color: #fff;">Your SaaS Product Name</h1>
          <p style="font-size: 1.25rem; color: rgba(255,255,255,0.8); margin-bottom: 2rem;">The #1 solution for modern businesses</p>
          <button style="background: linear-gradient(135deg, #ec4899, #f472b6); color: white; padding: 1rem 2rem; border: none; border-radius: 8px; font-size: 1.1rem; cursor: pointer;">Get Started Free</button>
        </section>
        <section style="padding: 3rem 2rem; background: #1a1a2e;">
          <h2 style="text-align: center; color: #fff; margin-bottom: 2rem;">Key Features</h2>
          <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 2rem; max-width: 1200px; margin: 0 auto;">
            <div style="background: rgba(255,255,255,0.05); padding: 2rem; border-radius: 12px; text-align: center;">
              <h3 style="color: #ec4899;">Feature 1</h3>
              <p style="color: rgba(255,255,255,0.7);">Description of your first feature</p>
            </div>
            <div style="background: rgba(255,255,255,0.05); padding: 2rem; border-radius: 12px; text-align: center;">
              <h3 style="color: #ec4899;">Feature 2</h3>
              <p style="color: rgba(255,255,255,0.7);">Description of your second feature</p>
            </div>
            <div style="background: rgba(255,255,255,0.05); padding: 2rem; border-radius: 12px; text-align: center;">
              <h3 style="color: #ec4899;">Feature 3</h3>
              <p style="color: rgba(255,255,255,0.7);">Description of your third feature</p>
            </div>
          </div>
        </section>
      HTML
      'lp_agency' => <<~HTML,
        <section class="hero-section" style="padding: 5rem 2rem; background: #0f0f1a; color: white; text-align: center;">
          <h1 style="font-size: 4rem; font-weight: bold; margin-bottom: 1rem;">Creative Agency</h1>
          <p style="font-size: 1.5rem; opacity: 0.8; margin-bottom: 2rem;">We bring your vision to life</p>
          <button style="background: white; color: #0f0f1a; padding: 1rem 2.5rem; border: none; border-radius: 50px; font-size: 1.1rem; cursor: pointer;">View Our Work</button>
        </section>
      HTML
      'lp_lead' => <<~HTML,
        <section style="padding: 4rem 2rem; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); text-align: center;">
          <h1 style="font-size: 2.5rem; color: white; margin-bottom: 1rem;">Get Your Free Guide</h1>
          <p style="color: rgba(255,255,255,0.9); margin-bottom: 2rem;">Enter your email to download</p>
          <form style="display: flex; gap: 1rem; justify-content: center; flex-wrap: wrap;">
            <input type="email" placeholder="your@email.com" style="padding: 1rem 1.5rem; border: none; border-radius: 8px; font-size: 1rem; width: 300px;">
            <button type="submit" style="background: #1a1a2e; color: white; padding: 1rem 2rem; border: none; border-radius: 8px; cursor: pointer;">Download Now</button>
          </form>
        </section>
      HTML
      'lp_event' => <<~HTML,
        <section style="padding: 4rem 2rem; background: #1a1a2e; text-align: center;">
          <span style="color: #ec4899; font-size: 0.875rem; text-transform: uppercase; letter-spacing: 2px;">Upcoming Event</span>
          <h1 style="font-size: 3rem; color: white; margin: 1rem 0;">Webinar Title</h1>
          <p style="color: rgba(255,255,255,0.7); margin-bottom: 2rem;">Date: Coming Soon | Time: TBD</p>
          <button style="background: linear-gradient(135deg, #ec4899, #f472b6); color: white; padding: 1rem 2rem; border: none; border-radius: 8px; font-size: 1.1rem; cursor: pointer;">Register Now</button>
        </section>
      HTML
      'lp_ecommerce' => <<~HTML
        <section style="padding: 4rem 2rem; background: white;">
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 4rem; max-width: 1200px; margin: 0 auto; align-items: center;">
            <div style="background: #f8f9fa; padding: 3rem; border-radius: 12px; text-align: center;">
              <span style="font-size: 4rem;">📦</span>
              <p style="color: #666; margin-top: 1rem;">Product Image</p>
            </div>
            <div>
              <h1 style="font-size: 2.5rem; color: #1a1a2e; margin-bottom: 1rem;">Product Name</h1>
              <p style="color: #666; margin-bottom: 2rem;">Amazing product description goes here</p>
              <p style="font-size: 2rem; color: #ec4899; font-weight: bold; margin-bottom: 2rem;">$99.00</p>
              <button style="background: #1a1a2e; color: white; padding: 1rem 2rem; border: none; border-radius: 8px; cursor: pointer; width: 100%;">Add to Cart</button>
            </div>
          </div>
        </section>
      HTML
    }
    
    template_html = templates[template_id]
    if template_html
      @landing_page.update(html_content: template_html)
    end
  end

  def ensure_html_structure(html)
    # Fix truncated HTML by ensuring proper structure
    result = html.dup
    
    # Close any unclosed script tags (common truncation issue)
    open_scripts = result.scan(/<script[^>]*>/i).count
    close_scripts = result.scan(/<\/script>/i).count
    if open_scripts > close_scripts
      (open_scripts - close_scripts).times do
        result += "\n</script>"
      end
      Rails.logger.warn "⚠️ Fixed #{open_scripts - close_scripts} unclosed script tag(s)"
    end
    
    # Close any unclosed style tags
    open_styles = result.scan(/<style[^>]*>/i).count
    close_styles = result.scan(/<\/style>/i).count
    if open_styles > close_styles
      (open_styles - close_styles).times do
        result += "\n</style>"
      end
      Rails.logger.warn "⚠️ Fixed #{open_styles - close_styles} unclosed style tag(s)"
    end
    
    # Close any unclosed form tags
    open_forms = result.scan(/<form[^>]*>/i).count
    close_forms = result.scan(/<\/form>/i).count
    if open_forms > close_forms
      (open_forms - close_forms).times do
        result += "\n</form>"
      end
      Rails.logger.warn "⚠️ Fixed #{open_forms - close_forms} unclosed form tag(s)"
    end
    
    # Close any unclosed select tags (common in truncated forms)
    open_selects = result.scan(/<select[^>]*>/i).count
    close_selects = result.scan(/<\/select>/i).count
    if open_selects > close_selects
      (open_selects - close_selects).times do
        result += "\n</select>"
      end
      Rails.logger.warn "⚠️ Fixed #{open_selects - close_selects} unclosed select tag(s)"
    end
    
    # Ensure </body> tag exists
    unless result.include?("</body>")
      result += "\n</body>"
      Rails.logger.warn "⚠️ Added missing </body> tag"
    end
    
    # Ensure </html> tag exists
    unless result.include?("</html>")
      result += "\n</html>"
      Rails.logger.warn "⚠️ Added missing </html> tag"
    end
    
    result
  end

  def sanitize_form_attributes(html)
    # Remove action and method attributes from forms to prevent native submission
    sanitized = html.dup
    
    # Remove action attributes from form tags
    # Match: action="...", action='...', action=...
    sanitized.gsub!(/(<form[^>]*)\s+action\s*=\s*["'][^"']*["']/i, '\1')
    sanitized.gsub!(/(<form[^>]*)\s+action\s*=\s*[^\s>]+/i, '\1')
    
    # Remove method attributes from form tags
    sanitized.gsub!(/(<form[^>]*)\s+method\s*=\s*["'][^"']*["']/i, '\1')
    sanitized.gsub!(/(<form[^>]*)\s+method\s*=\s*[^\s>]+/i, '\1')
    
    # Remove inline onsubmit handlers
    sanitized.gsub!(/(<form[^>]*)\s+onsubmit\s*=\s*["'][^"']*["']/i, '\1')
    
    # Also handle cases where attribute is right after <form (no space before)
    # e.g., <form action="..."> or <formmethod="...">
    sanitized.gsub!(/<form\s+action\s*=\s*["'][^"']*["']/i, '<form')
    sanitized.gsub!(/<form\s+method\s*=\s*["'][^"']*["']/i, '<form')
    
    Rails.logger.info "✅ Form attributes sanitized for preview"
    sanitized
  end

  def inject_page_font(html, page_font)
    return html if page_font.blank?
    
    # Build the Google Font link and style tag
    font_link = "<link href=\"https://fonts.googleapis.com/css2?family=#{ERB::Util.url_encode(page_font)}:wght@300;400;500;600;700;800;900&display=swap\" rel=\"stylesheet\">"
    font_style = <<~CSS
      <style id="page-font-style">
        body, body * {
          font-family: '#{page_font}', sans-serif !important;
        }
        /* Allow icons to keep their font */
        i[class*="fa-"],
        [class*="icon"],
        .material-icons {
          font-family: inherit !important;
        }
      </style>
    CSS
    
    # Inject into <head> if present, otherwise prepend to html
    if html.include?('</head>')
      html.sub('</head>', "#{font_link}\n#{font_style}\n</head>")
    else
      "#{font_link}\n#{font_style}\n#{html}"
    end
  end

  def inject_form_handling_script(html, slug)
    # Skip if script is already present
    return html if html.include?('data-lp-form-handler')
    
    # First, strip any malformed scripts from AI output that could cause syntax errors
    # This removes any script that doesn't have a proper closing tag
    cleaned_html = strip_malformed_scripts(html)

    # Use type="module" for complete isolation from other scripts on the page
    # Modules have their own scope and won't be affected by syntax errors in other scripts
    form_script = <<~JAVASCRIPT
      <script type="module" data-lp-form-handler="true">
      try {
        const slug = "#{slug}";
        const isPreview = location.pathname.includes("/preview") || location.pathname.includes("/landing_pages/");
        
        function handleSubmit(form) {
          const data = new FormData(form);
          const btn = form.querySelector("button[type=submit], input[type=submit], button:not([type])");
          const origText = btn ? (btn.textContent || btn.value) : "";
          
          if (btn) {
            btn.disabled = true;
            btn.tagName === "BUTTON" ? btn.textContent = "Sending..." : btn.value = "Sending...";
          }
          
          let url = "/api/v1/landing_pages/" + slug + "/submit";
          if (isPreview) url += "?preview=true";
          
          fetch(url, { method: "POST", body: data, headers: { "X-Requested-With": "XMLHttpRequest" } })
            .then(r => r.json())
            .then(d => {
              if (d.success) {
                form.innerHTML = '<div style="padding:20px;background:#d4edda;border:1px solid #c3e6cb;border-radius:8px;color:#155724"><h4 style="margin:0 0 10px">Thank you!</h4><p style="margin:0">' + d.message + '</p></div>';
              } else {
                alert(d.message || "Error submitting form.");
                if (btn) { btn.disabled = false; btn.tagName === "BUTTON" ? btn.textContent = origText : btn.value = origText; }
              }
            })
            .catch(e => {
              console.error("Form error:", e);
              alert("Error submitting form. Please try again.");
              if (btn) { btn.disabled = false; btn.tagName === "BUTTON" ? btn.textContent = origText : btn.value = origText; }
            });
        }
        
        function init() {
          document.querySelectorAll("form:not([data-lp-bound])").forEach(form => {
            const action = form.getAttribute("action");
            if (action && action.startsWith("http")) return;
            
            form.removeAttribute("action");
            form.removeAttribute("method");
            form.setAttribute("data-lp-bound", "1");
            
            form.querySelectorAll("input,textarea,select").forEach(el => {
              if (!el.name && el.id) el.name = el.id;
            });
            
            form.addEventListener("submit", e => {
              e.preventDefault();
              e.stopPropagation();
              handleSubmit(form);
              return false;
            }, true);
          });
        }
        
        if (document.readyState === "loading") {
          document.addEventListener("DOMContentLoaded", init);
        } else {
          init();
        }
        window.addEventListener("load", init);
      } catch(e) { console.error("LP form handler:", e); }
      </script>
    JAVASCRIPT

    # Inject before </body> or at end
    if cleaned_html.include?("</body>")
      cleaned_html.sub("</body>", "#{form_script}\n</body>")
    else
      cleaned_html + form_script
    end
  end
  
  def strip_malformed_scripts(html)
    # Remove any script tags that contain obvious syntax issues
    result = html.dup
    
    # Find and validate each script tag
    result.gsub!(/<script[^>]*>(.*?)<\/script>/im) do |match|
      script_content = $1
      
      # Check for obviously incomplete code patterns
      incomplete_patterns = [
        /function\s+\w+\s*\([^)]*\)\s*\{\s*[^}]*\z/,  # Unclosed function
        /if\s*\([^)]*\)\s*\{\s*[^}]*\z/,              # Unclosed if
        /for\s*\([^)]*\)\s*\{\s*[^}]*\z/,             # Unclosed for
        /while\s*\([^)]*\)\s*\{\s*[^}]*\z/,           # Unclosed while
        /\{\s*[^}]*\z/,                               # Unclosed brace at end
        /['"][^'"]*\z/,                               # Unclosed string
      ]
      
      is_malformed = incomplete_patterns.any? { |pattern| script_content.match?(pattern) }
      
      # Also check for balanced braces
      open_braces = script_content.count('{')
      close_braces = script_content.count('}')
      is_malformed ||= (open_braces != close_braces)
      
      if is_malformed
        Rails.logger.warn "⚠️ Removed malformed script tag (#{open_braces} open, #{close_braces} close braces)"
        "<!-- Removed malformed script -->"
      else
        match
      end
    end
    
    result
  end

  def strip_editing_attributes(html_content)
    # Remove all editing-related attributes and classes for clean preview
    clean_html = html_content.dup

    # Remove contenteditable attributes
    clean_html.gsub!(/\s*contenteditable\s*=\s*["']true["']/i, "")
    clean_html.gsub!(/\s*contenteditable\s*=\s*["']false["']/i, "")
    clean_html.gsub!(/\s*contenteditable/i, "")

    # Remove spellcheck attributes
    clean_html.gsub!(/\s*spellcheck\s*=\s*["']false["']/i, "")
    clean_html.gsub!(/\s*spellcheck\s*=\s*["']true["']/i, "")

    # Remove data-original-content attributes
    clean_html.gsub!(/\s*data-original-content\s*=\s*["'][^"']*["']/i, "")

    # Remove editing-related classes
    clean_html.gsub!(/\s*editable-text\s*/, " ")
    clean_html.gsub!(/\s*editable-image\s*/, " ")
    clean_html.gsub!(/\s*editable-element\s*/, " ")

    # FIX: Add 'animated' class to all 'animate-on-scroll' elements so they're visible
    # Without this, elements with animate-on-scroll have opacity:0 and stay invisible
    clean_html.gsub!(/class\s*=\s*["']([^"']*animate-on-scroll[^"']*)["']/) do |match|
      classes = $1
      if classes.include?('animated')
        match
      else
        "class=\"#{classes} animated\""
      end
    end

    # Clean up any double spaces left by class removal
    # IMPORTANT: Only collapse whitespace OUTSIDE of <style> and <script> tags
    # to avoid breaking CSS/JS syntax
    clean_html = collapse_whitespace_safely(clean_html)
    clean_html.gsub!(/class\s*=\s*["']\s*["']/, "")

    clean_html
  end

  # Collapse whitespace only outside of <style> and <script> tags
  def collapse_whitespace_safely(html)
    # Split by style/script tags, only collapse whitespace outside them
    result = ""
    remaining = html.dup
    
    while remaining.present?
      # Find the next style or script tag
      match = remaining.match(/(<style[^>]*>.*?<\/style>|<script[^>]*>.*?<\/script>)/mi)
      
      if match
        # Process the text before the tag (collapse whitespace)
        before_tag = remaining[0...match.begin(0)]
        result += before_tag.gsub(/\s+/, " ")
        
        # Keep the style/script block intact (no whitespace collapse)
        result += match[0]
        
        # Continue with the rest
        remaining = remaining[match.end(0)..]
      else
        # No more style/script tags, collapse the rest
        result += remaining.gsub(/\s+/, " ")
        break
      end
    end
    
    result
  end

  def generate_title_and_slug
    # Generate title using AI based on description
    description = @landing_page.description || "landing page"

    begin
      # Use ClaudeService with proper system and user message format
      system_prompt = "You are a marketing expert who creates compelling landing page titles."
      user_message = "Based on this landing page description, create a compelling 3-8 word title:

\"#{description}\"

Return only the title, nothing else. Make it clear, compelling, and action-oriented."

      response = ClaudeService.new.send_message(system_prompt, user_message)
      title = response.strip.gsub(/["""]/, "")

      # Fallback if AI response is too long or empty
      if title.blank? || title.length > 100
        title = description.split(".").first&.strip || "New Landing Page"
        title = title[0..50] if title.length > 50
      end

      @landing_page.title = title

      # Generate unique slug from title
      base_slug = title.parameterize
      base_slug = "landing-page" if base_slug.blank?

      # Ensure uniqueness
      slug = base_slug
      counter = 1
      while LandingPage.where(slug: slug).exists?
        slug = "#{base_slug}-#{counter}"
        counter += 1
      end

      @landing_page.slug = slug

      Rails.logger.info "Successfully generated title: '#{title}' and slug: '#{slug}'"

    rescue => e
      Rails.logger.error "Error generating title and slug: #{e.message}"
      Rails.logger.error e.backtrace.join("\n")

      # Fallback to simple title and slug
      @landing_page.title = "New Landing Page"
      base_slug = "landing-page-#{Time.current.to_i}"
      @landing_page.slug = base_slug
    end
  end

  def landing_page_params
    params.require(:landing_page).permit(
      :title,
      :slug,
      :description,
      :campaign_id,
      :html_content,
      :status,
      :meta_description,
      :meta_keywords,
      :clarification_questions,
      :clarification_answers,
      :page_font,
      metadata: [:page_font]
    )
  end

  def track_landing_page_view
    # Implement view tracking logic here
    # Could record visitor info, referrer, etc.
  end

  def generate_initial_content
    # Build comprehensive context for AI generation
    context = {
      business_profile: @business_profile,
      design_preferences: {
        page_type: @landing_page.page_type,
        tone_preference: @landing_page.tone_preference,
        content_length: @landing_page.content_length,
        primary_color: @landing_page.primary_color,
        secondary_color: @landing_page.secondary_color,
        font_family: @landing_page.font_family
      },
      features: {
        include_testimonials: @landing_page.include_testimonials,
        include_features: @landing_page.include_features,
        include_faq: @landing_page.include_faq,
        include_pricing: @landing_page.include_pricing,
        include_about: @landing_page.include_about,
        include_contact: @landing_page.include_contact
      }
    }

    # Use the enhanced AI generation job with all context
    AgentGenerateLandingPageJob.perform_later(
      @landing_page.id,
      @landing_page.description,
      current_entity.id,
      @business_profile&.id,
      @landing_page.page_type,
      context
    )
  end
end
