# frozen_string_literal: true

# GenerateModelCodeTool
#
# Platform Factory tool that generates Ruby model code
# from a schema definition.
#
class Tools::GenerateModelCodeTool < Tools::BaseTool
  def self.metadata
    {
      name: 'generate_model_code',
      description: 'Generates Ruby model code from a schema definition. Creates the model class with associations, validations, scopes, and instance methods.',
      category: 'platform_factory',
      input_schema: {
        type: 'object',
        properties: {
          module_slug: {
            type: 'string',
            description: 'Slug of the module this model belongs to'
          },
          model_schema: {
            type: 'object',
            description: 'Schema definition for the model (from design_module_schema)'
          }
        },
        required: %w[module_slug model_schema]
      }
    }
  end

  def execute(args)
    log_execution(args)

    module_slug = get_arg(args, :module_slug)
    model_schema = get_arg(args, :model_schema)

    return error_response('Module slug is required') if module_slug.blank?
    return error_response('Model schema is required') if model_schema.blank?

    # Find the module
    app_module = AppModule.find_by(entity: entity, slug: module_slug)
    return error_response("Module not found: #{module_slug}") unless app_module

    # Normalize schema
    schema = normalize_schema(model_schema)

    # Generate the model code
    model_code = generate_model_code(schema, app_module)

    # Create the ModuleCode record
    code_record = ModuleCode.find_or_initialize_by(
      app_module: app_module,
      entity: entity,
      name: schema[:name],
      code_type: 'model'
    )

    code_record.update!(
      content: model_code,
      schema_definition: schema,
      status: 'generated'
    )

    # Validate syntax
    syntax_valid = code_record.validate_syntax!

    success_response(
      module_code_id: code_record.id,
      model_name: schema[:name],
      table_name: schema[:table_name],
      code: model_code,
      syntax_valid: syntax_valid,
      status: code_record.status,
      message: "Generated model code for #{schema[:name]}",
      next_step: syntax_valid ? 'Use register_dynamic_model to load the model' : 'Fix syntax errors and regenerate'
    )
  end

  private

  def normalize_schema(schema)
    schema = schema.transform_keys(&:to_sym) if schema.is_a?(Hash)
    
    {
      name: schema[:name],
      table_name: schema[:table_name] || schema[:name].to_s.underscore.pluralize,
      description: schema[:description],
      fields: (schema[:fields] || []).map { |f| f.transform_keys(&:to_sym) },
      associations: (schema[:associations] || []).map { |a| a.transform_keys(&:to_sym) },
      indexes: (schema[:indexes] || []).map { |i| i.transform_keys(&:to_sym) },
      validations: (schema[:validations] || []).map { |v| v.transform_keys(&:to_sym) },
      scopes: (schema[:scopes] || []).map { |s| s.transform_keys(&:to_sym) }
    }
  end

  def generate_model_code(schema, app_module)
    namespace = "Modules::#{app_module.slug.camelize}"
    
    code = <<~RUBY
      # frozen_string_literal: true
      
      # Generated by Platform Factory for module: #{app_module.name}
      # Model: #{schema[:name]}
      # Description: #{schema[:description]}
      # Generated at: #{Time.current.iso8601}
      
      module #{namespace}
        class #{schema[:name]} < ApplicationRecord
          self.table_name = '#{schema[:table_name]}'
          
          # ============================================
          # ASSOCIATIONS
          # ============================================
          
          #{generate_associations(schema[:associations])}
          
          # ============================================
          # VALIDATIONS
          # ============================================
          
          #{generate_validations(schema[:validations])}
          
          # ============================================
          # SCOPES
          # ============================================
          
          #{generate_scopes(schema[:scopes])}
          
          # ============================================
          # INSTANCE METHODS
          # ============================================
          
          def to_s
            #{generate_to_s(schema)}
          end
        end
      end
    RUBY

    code.strip
  end

  def generate_associations(associations)
    return '# No associations defined' if associations.blank?

    associations.map do |assoc|
      type = assoc[:type]
      model = assoc[:model]
      options = []

      options << "optional: #{assoc[:optional]}" if assoc[:optional].present?
      options << "class_name: '#{assoc[:class_name]}'" if assoc[:class_name].present?
      options << "foreign_key: '#{assoc[:foreign_key]}'" if assoc[:foreign_key].present?
      options << "dependent: :#{assoc[:dependent]}" if assoc[:dependent].present?

      if options.any?
        "#{type} :#{model.underscore}, #{options.join(', ')}"
      else
        "#{type} :#{model.underscore}"
      end
    end.join("\n    ")
  end

  def generate_validations(validations)
    return '# No validations defined' if validations.blank?

    validations.map do |val|
      case val[:type]
      when 'presence'
        fields = Array(val[:fields] || val[:field]).map { |f| ":#{f}" }.join(', ')
        "validates #{fields}, presence: true"
      when 'uniqueness'
        field = val[:field]
        scope = val[:scope] ? ", scope: :#{val[:scope]}" : ''
        "validates :#{field}, uniqueness: { scope: :entity_id#{scope} }"
      when 'numericality'
        field = val[:field]
        opts = val[:options] || {}
        opt_str = opts.map { |k, v| "#{k}: #{v}" }.join(', ')
        "validates :#{field}, numericality: { #{opt_str} }"
      when 'inclusion'
        field = val[:field]
        # Check both val[:in] and val[:options][:in] for the values array
        in_values = val[:in] || val.dig(:options, :in) || val.dig(:options, 'in') || []
        values = in_values.map { |v| v.is_a?(String) ? "'#{v}'" : v }.join(', ')
        "validates :#{field}, inclusion: { in: [#{values}] }"
      when 'length'
        field = val[:field]
        opts = val[:options] || {}
        opt_str = opts.map { |k, v| "#{k}: #{v}" }.join(', ')
        "validates :#{field}, length: { #{opt_str} }"
      else
        "# Unknown validation type: #{val[:type]}"
      end
    end.join("\n    ")
  end

  def generate_scopes(scopes)
    return '# No scopes defined' if scopes.blank?

    scopes.map do |scope|
      "scope :#{scope[:name]}, -> { #{scope[:condition]} }"
    end.join("\n    ")
  end

  def generate_to_s(schema)
    # Try to find a good field to use for string representation
    name_fields = %w[name title label description]
    display_field = schema[:fields].find { |f| name_fields.include?(f[:name].to_s) }
    
    if display_field
      display_field[:name].to_s
    else
      '"#<#{self.class.name}:#{id}>"'
    end
  end
end


