# frozen_string_literal: true

module Tools
  # GetPlatformCapabilitiesTool - Provides Amos with knowledge about the platform's capabilities
  #
  # This tool enables platform self-awareness by giving the AI agent access to
  # documentation about how different features work, what field types are supported,
  # how canvases are rendered, and other architectural details.
  #
  class GetPlatformCapabilitiesTool < BaseTool
    def self.read_only?
      true
    end

    def self.metadata
      {
        name: "get_platform_capabilities",
        description: "Retrieves documentation about how the platform works internally. Use this to understand supported field types, canvas rendering, module architecture, and other technical capabilities before creating or fixing modules.",
        category: "platform_knowledge",
        input_schema: {
          type: "object",
          properties: {
            topic: {
              type: "string",
              enum: [
                "form_rendering",
                "field_types", 
                "canvas_types",
                "module_architecture",
                "reference_fields",
                "module_creation",
                "module_troubleshooting",
                "available_models",
                "tool_system",
                "all"
              ],
              description: "The topic to get information about. Use 'all' for a complete overview."
            }
          },
          required: ["topic"]
        }
      }
    end

    def execute(args)
      log_execution(args)
      topic = get_arg(args, :topic)
      
      if error = validate_required_args(args, [:topic])
        return error
      end

      capabilities = case topic
      when "all"
        {
          form_rendering: form_rendering_docs,
          field_types: field_types_docs,
          canvas_types: canvas_types_docs,
          module_architecture: module_architecture_docs,
          reference_fields: reference_fields_docs,
          module_creation: module_creation_docs,
          module_troubleshooting: module_troubleshooting_docs,
          available_models: available_models_docs,
          tool_system: tool_system_docs
        }
      when "form_rendering"
        form_rendering_docs
      when "field_types"
        field_types_docs
      when "canvas_types"
        canvas_types_docs
      when "module_architecture"
        module_architecture_docs
      when "reference_fields"
        reference_fields_docs
      when "module_creation"
        module_creation_docs
      when "module_troubleshooting"
        module_troubleshooting_docs
      when "available_models"
        available_models_docs
      when "tool_system"
        tool_system_docs
      else
        return error_response("Unknown topic: #{topic}")
      end

      success_response(
        topic: topic,
        capabilities: capabilities
      )
    end

    private

    def form_rendering_docs
      {
        summary: "Forms in modules are DYNAMICALLY GENERATED by scout_controller.rb, NOT from html_content",
        key_points: [
          "Form canvases are rendered by the render_module_form_canvas method",
          "The html_content field in ModuleCanvas is NOT used for form rendering",
          "Forms are generated from the 'fields' array in canvas.metadata",
          "If a field is missing from canvas.metadata['fields'], it won't appear in the form",
          "When adding fields to a module, you MUST also update the form canvas metadata"
        ],
        how_it_works: {
          step_1: "Controller finds the ModuleCanvas for the form",
          step_2: "Reads fields from canvas.metadata['fields'] (or falls back to module schema)",
          step_3: "For each field, generates appropriate HTML input based on field_type",
          step_4: "Reference fields become <select> dropdowns populated from the referenced model",
          step_5: "Form submission sends data to Amos via chat message"
        },
        important: "To fix a form, update the metadata['fields'] array, NOT the html_content"
      }
    end

    def field_types_docs
      {
        summary: "Supported field types for module schemas and form rendering",
        supported_types: {
          string: {
            renders_as: "text input",
            use_for: "short text, names, titles, single-line values"
          },
          text: {
            renders_as: "textarea",
            use_for: "long text, descriptions, notes, multi-line content"
          },
          integer: {
            renders_as: "number input",
            use_for: "whole numbers, counts, IDs"
          },
          decimal: {
            renders_as: "number input",
            use_for: "monetary values, percentages, measurements"
          },
          boolean: {
            renders_as: "checkbox",
            use_for: "yes/no, true/false, enabled/disabled flags"
          },
          date: {
            renders_as: "date picker",
            use_for: "dates without time (birthdays, due dates)"
          },
          datetime: {
            renders_as: "datetime-local input",
            use_for: "dates with time (scheduled events, timestamps)"
          },
          json: {
            renders_as: "textarea with monospace font",
            use_for: "complex nested data, arrays, flexible structures"
          },
          enum: {
            renders_as: "select dropdown",
            use_for: "fixed set of options (status, category, type)",
            requires: "options array in field definition"
          },
          select: {
            renders_as: "select dropdown",
            use_for: "same as enum - fixed options",
            requires: "options array in field definition"
          },
          reference: {
            renders_as: "select dropdown populated from another model",
            use_for: "foreign keys, relationships to other records",
            requires: "reference_model or references in field definition"
          }
        },
        field_definition_example: {
          name: "status",
          field_type: "enum",
          label: "Status",
          required: true,
          options: ["draft", "active", "completed"],
          default_value: "draft",
          description: "Current status of the record"
        },
        reference_field_example: {
          name: "landing_page_id",
          field_type: "reference",
          reference_model: "LandingPage",
          label: "Landing Page",
          required: false,
          description: "The landing page this record is associated with"
        }
      }
    end

    def canvas_types_docs
      {
        summary: "Different canvas types available for modules",
        types: {
          list: {
            description: "Data grid/table view showing multiple records",
            renders: "Table with columns for display_fields",
            supports: "filtering, sorting, pagination, row actions"
          },
          form: {
            description: "Form for creating/editing a single record",
            renders: "Dynamically generated form inputs based on field definitions",
            supports: "all field types, validation, save/cancel actions"
          },
          detail: {
            description: "Read-only view of a single record",
            renders: "Formatted display of record data",
            supports: "edit button, related records"
          },
          calendar: {
            description: "Calendar view for date-based records",
            renders: "FullCalendar grid with events",
            requires: "date or datetime field for event positioning"
          },
          kanban: {
            description: "Kanban board for status-based workflows",
            renders: "Columns with draggable cards",
            requires: "status/enum field for column grouping"
          },
          dashboard: {
            description: "Summary view with metrics and charts",
            renders: "Cards, charts, statistics",
            supports: "aggregations, visualizations"
          }
        },
        rendering_note: "list and form canvases are dynamically rendered. Other types use html_content."
      }
    end

    def module_architecture_docs
      {
        summary: "How custom modules are structured in the platform",
        components: {
          AppModule: {
            description: "Main module record containing metadata and schema",
            key_fields: ["slug", "name", "metadata (contains schema)", "status", "icon"]
          },
          ModuleCanvas: {
            description: "UI views for the module (list, form, etc.)",
            key_fields: ["canvas_type", "slug", "metadata (contains fields, display_fields)"]
          },
          ModuleCode: {
            description: "Generated code for database table and model",
            key_fields: ["code_type (model)", "schema_definition (columns)", "status"]
          },
          ModuleAction: {
            description: "Custom buttons and actions for the module",
            key_fields: ["action_type", "behavior_config", "location", "visibility_rules"]
          }
        },
        data_flow: {
          schema: "AppModule.metadata['schema']['fields'] defines the data structure",
          form_canvas: "ModuleCanvas.metadata['fields'] drives form rendering",
          list_canvas: "ModuleCanvas.metadata['display_fields'] determines visible columns",
          database: "ModuleCode.schema_definition defines the actual database table"
        },
        critical_sync: "Schema fields, canvas fields, and database columns must stay in sync!"
      }
    end

    def reference_fields_docs
      {
        summary: "How to properly create reference (foreign key) fields",
        definition: {
          name: "Must end with _id (e.g., landing_page_id, contact_id)",
          field_type: "Must be 'reference'",
          reference_model: "Must specify the model class (e.g., 'LandingPage', 'Contact')"
        },
        example: {
          name: "landing_page_id",
          field_type: "reference",
          reference_model: "LandingPage",
          label: "Landing Page",
          required: false,
          description: "Select a landing page"
        },
        supported_reference_models: [
          "LandingPage",
          "Contact",
          "Campaign",
          "User",
          "EmailTemplate",
          "Opportunity"
        ],
        how_dropdowns_work: {
          step_1: "render_reference_field method detects reference type",
          step_2: "Looks up the model class (e.g., LandingPage)",
          step_3: "Queries records scoped to current entity",
          step_4: "Builds <select> with options using name/title/email as display",
          step_5: "Pre-selects current value if editing"
        },
        common_mistakes: [
          "Missing field_type: 'reference' - falls through to text input",
          "Missing reference_model - cannot populate dropdown",
          "Field not in canvas metadata - doesn't appear in form",
          "Field not in database - save fails"
        ]
      }
    end

    def module_creation_docs
      {
        summary: "Proper workflow for creating modules that work correctly",
        workflow: {
          step_1: {
            tool: "start_module_design",
            purpose: "Initiate design session and gather requirements"
          },
          step_2: {
            tool: "propose_module_schema", 
            purpose: "Define fields with correct types, including reference_model for references"
          },
          step_3: {
            tool: "approve_module_design",
            purpose: "Creates AppModule, ModuleCode, ModuleCanvases with synced metadata"
          }
        },
        checklist_before_approval: [
          "All fields have valid field_type",
          "Reference fields have reference_model specified",
          "Enum fields have options array",
          "Required fields are marked required: true",
          "Labels are human-readable"
        ],
        after_creation: [
          "Verify with diagnose_module tool",
          "Test the form canvas loads correctly",
          "Test reference dropdowns are populated",
          "Test creating and editing records"
        ]
      }
    end

    def module_troubleshooting_docs
      {
        summary: "Common module issues and how to fix them",
        issues: {
          form_not_loading: {
            symptoms: "Form canvas shows blank or error",
            causes: ["Canvas metadata missing fields", "JavaScript error", "Missing database table"],
            fix: "Use diagnose_module tool, then update_module to fix canvas metadata"
          },
          field_shows_as_text_input: {
            symptoms: "Reference field shows text input instead of dropdown",
            causes: ["Missing field_type: 'reference'", "Missing reference_model", "Field not in canvas metadata"],
            fix: "Update field definition with correct type and reference_model, sync to canvas"
          },
          dropdown_empty: {
            symptoms: "Select dropdown has no options",
            causes: ["reference_model not found", "No records in referenced model", "Entity scoping issue"],
            fix: "Verify reference_model is correct, check if records exist"
          },
          field_not_in_form: {
            symptoms: "Field exists in schema but not in form",
            causes: ["Field missing from canvas.metadata['fields']"],
            fix: "Use update_module with action: 'update_canvas' to add field to metadata"
          },
          save_fails: {
            symptoms: "Error when saving record",
            causes: ["Database column missing", "Validation error", "Type mismatch"],
            fix: "Check ModuleCode schema_definition matches schema fields"
          }
        },
        diagnostic_tool: "Use diagnose_module tool to automatically check for common issues"
      }
    end

    def available_models_docs
      {
        summary: "Core platform models available for reference fields",
        models: {
          LandingPage: {
            description: "Marketing landing pages",
            display_field: "name",
            common_use: "A/B testing, campaign tracking"
          },
          Contact: {
            description: "Customer/lead contacts",
            display_field: "email or name",
            common_use: "CRM, email sequences"
          },
          Campaign: {
            description: "Marketing campaigns",
            display_field: "name",
            common_use: "Attribution, reporting"
          },
          User: {
            description: "Platform users",
            display_field: "email",
            common_use: "Assigned to, created by"
          },
          EmailTemplate: {
            description: "Email templates",
            display_field: "name",
            common_use: "Email campaigns"
          },
          Opportunity: {
            description: "Sales opportunities",
            display_field: "name",
            common_use: "Sales pipeline"
          }
        },
        custom_modules: "Custom modules can also be referenced once created and deployed"
      }
    end

    def tool_system_docs
      {
        summary: "How the tool system works for module management",
        module_tools: {
          start_module_design: "Initiates interactive module design session",
          propose_module_schema: "Proposes field structure for approval",
          refine_module_schema: "Modifies schema based on feedback",
          approve_module_design: "Finalizes and builds the module",
          update_module: "Updates existing modules (add fields, fix canvases)",
          diagnose_module: "Checks module health and identifies issues",
          get_platform_capabilities: "This tool - explains how platform works"
        },
        update_module_actions: {
          add_field: "Add new field to schema AND syncs to canvases",
          remove_field: "Remove field from schema",
          update_field: "Modify field properties",
          update_canvas: "Update canvas metadata directly",
          fix_canvas_buttons: "Regenerate canvas with working buttons",
          regenerate_model: "Rebuild model from schema"
        },
        best_practices: [
          "Always use diagnose_module after making changes",
          "Use get_platform_capabilities before creating complex modules",
          "Test forms after adding reference fields",
          "Keep schema, canvas metadata, and database in sync"
        ]
      }
    end
  end
end


