# frozen_string_literal: true

# AgentGoal - Autonomous goals generated by the Desire Engine
#
# These are goals that the platform generates for itself, without human intervention.
# They can target agents, modules, tools, or the entity as a whole.
#
# Goal Types:
# - improvement: Make an underperforming component better
# - expansion: Build a new capability to address an unmet need
# - maintenance: Fix, clean, or optimize something
# - learning: Research and acquire new knowledge
# - social: Help another agent or improve collaboration
#
# Integration with existing systems:
# - Can trigger AgentSchoolEnrollment for training goals
# - Can trigger AgentAbTest for improvement experiments
# - Uses EvolutionService for analysis
# - Links to ScheduledAgentTask for execution
#
class AgentGoal < ApplicationRecord
  belongs_to :entity
  belongs_to :agent_plugin, optional: true  # null = entity-wide goal
  belongs_to :created_by_agent, class_name: 'AgentPlugin', optional: true
  belongs_to :execution_task, class_name: 'ScheduledAgentTask', optional: true
  belongs_to :school_enrollment, class_name: 'AgentSchoolEnrollment', optional: true
  
  has_many :agent_ab_tests, dependent: :nullify
  has_many :lifecycle_events, class_name: 'AgentLifecycleEvent', 
           foreign_key: :triggered_by_goal_id, dependent: :nullify
  has_many :platform_anomalies, foreign_key: :triggered_goal_id, dependent: :nullify
  has_many :school_enrollments, class_name: 'AgentSchoolEnrollment',
           foreign_key: :triggered_by_goal_id, dependent: :nullify

  # Goal types
  GOAL_TYPES = %w[improvement expansion maintenance learning social].freeze
  
  # Statuses
  STATUSES = %w[pending scheduled in_progress completed failed cancelled].freeze
  
  # Sources
  SOURCES = %w[desire_engine user_request system_detection agent_reflection evolution_cycle perception].freeze

  validates :goal_type, presence: true, inclusion: { in: GOAL_TYPES }
  validates :title, presence: true
  validates :status, presence: true, inclusion: { in: STATUSES }
  validates :priority, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 100 }
  validates :source, inclusion: { in: SOURCES }, allow_nil: true

  scope :pending, -> { where(status: 'pending') }
  scope :scheduled, -> { where(status: 'scheduled') }
  scope :in_progress, -> { where(status: 'in_progress') }
  scope :completed, -> { where(status: 'completed') }
  scope :failed, -> { where(status: 'failed') }
  scope :cancelled, -> { where(status: 'cancelled') }
  scope :active, -> { where(status: %w[pending scheduled in_progress]) }
  scope :by_type, ->(type) { where(goal_type: type) }
  scope :by_priority, -> { order(priority: :desc) }
  scope :due_now, -> { where('scheduled_for <= ?', Time.current).where(status: 'scheduled') }
  scope :for_agent, ->(agent) { where(agent_plugin: agent) }
  scope :entity_wide, -> { where(agent_plugin_id: nil) }
  scope :recent, -> { order(created_at: :desc) }
  scope :high_priority, -> { where('priority >= ?', 70) }

  # ═══════════════════════════════════════════════════════════════════════════
  # LIFECYCLE
  # ═══════════════════════════════════════════════════════════════════════════

  def schedule!(scheduled_for: 1.hour.from_now, task: nil)
    attrs = { status: 'scheduled', scheduled_for: scheduled_for }
    attrs[:execution_task] = task if task
    update!(attrs)
  end

  def start!
    update!(status: 'in_progress', started_at: Time.current)
  end

  def complete!(result = {})
    update!(
      status: 'completed',
      completed_at: Time.current,
      execution_result: result
    )
  end

  def fail!(error_message)
    update!(
      status: 'failed',
      completed_at: Time.current,
      execution_result: execution_result.merge(error: error_message)
    )
  end

  def cancel!(reason = nil)
    update!(
      status: 'cancelled',
      completed_at: Time.current,
      execution_result: execution_result.merge(cancellation_reason: reason)
    )
  end

  # ═══════════════════════════════════════════════════════════════════════════
  # STATUS HELPERS
  # ═══════════════════════════════════════════════════════════════════════════

  def pending?
    status == 'pending'
  end

  def scheduled?
    status == 'scheduled'
  end

  def in_progress?
    status == 'in_progress'
  end

  def completed?
    status == 'completed'
  end

  def failed?
    status == 'failed'
  end

  def active?
    %w[pending scheduled in_progress].include?(status)
  end

  # ═══════════════════════════════════════════════════════════════════════════
  # TARGET HELPERS
  # ═══════════════════════════════════════════════════════════════════════════

  def target
    return nil unless target_type.present? && target_id.present?
    target_type.constantize.find_by(id: target_id)
  end

  def target=(record)
    if record.nil?
      self.target_type = nil
      self.target_id = nil
    else
      self.target_type = record.class.name
      self.target_id = record.id
    end
  end

  # ═══════════════════════════════════════════════════════════════════════════
  # EXECUTION HELPERS
  # ═══════════════════════════════════════════════════════════════════════════

  # Create a scheduled task to execute this goal
  def create_execution_task!(executor_agent: nil, prompt: nil)
    task_prompt = prompt || build_execution_prompt
    
    task = ScheduledAgentTask.create!(
      entity: entity,
      user: entity.users.first,
      agent_plugin: executor_agent || find_best_executor,
      name: "Goal: #{title.truncate(50)}",
      description: description,
      task_type: 'custom',
      prompt: task_prompt,
      schedule_type: 'once',
      next_run_at: scheduled_for || 5.minutes.from_now,
      enabled: true,
      execution_mode: 'agent_only'
    )
    
    update!(execution_task: task, status: 'scheduled')
    task
  end

  # Trigger Agent School enrollment for training goals
  def trigger_school_enrollment!
    return nil unless goal_type == 'improvement' && target.is_a?(AgentPlugin)
    return school_enrollment if school_enrollment.present?
    
    school = Collaboration::AgentSchool.new
    result = school.enroll(target)
    
    if result[:success]
      update!(school_enrollment: result[:enrollment])
      result[:enrollment]
    else
      nil
    end
  end

  # Create an A/B test experiment for this goal
  def create_experiment!(control_config:, variant_config:)
    AgentAbTest.create!(
      entity: entity,
      agent_goal: self,
      control_agent: target,
      variant_agent: target,  # Same agent, different config
      target_tasks: 100,
      status: 'pending',
      metadata: {
        goal_id: id,
        control_config: control_config,
        variant_config: variant_config
      }
    )
  end

  # ═══════════════════════════════════════════════════════════════════════════
  # METRICS
  # ═══════════════════════════════════════════════════════════════════════════

  def success_criteria_met?
    return false if success_criteria.blank?
    return false if current_metrics.blank?
    
    success_criteria.all? do |key, target_value|
      current_value = current_metrics[key] || execution_result.dig('final_metrics', key)
      compare_metric(current_value, target_value)
    end
  end

  def progress_percent
    return 0 if target_metrics.blank? || current_metrics.blank?
    return 100 if completed?
    
    metrics_count = target_metrics.keys.count
    return 0 if metrics_count.zero?
    
    met_count = target_metrics.count do |key, target_value|
      current_value = current_metrics[key]
      compare_metric(current_value, target_value)
    end
    
    (met_count.to_f / metrics_count * 100).round
  end

  def duration_minutes
    return nil unless started_at
    end_time = completed_at || Time.current
    ((end_time - started_at) / 60).round
  end

  private

  def compare_metric(current, target)
    return false if current.nil?
    
    case target
    when Hash
      if target['min']
        current >= target['min']
      elsif target['max']
        current <= target['max']
      elsif target['equals']
        current == target['equals']
      else
        true
      end
    else
      current >= target
    end
  end

  def build_execution_prompt
    <<~PROMPT
      Execute the following goal:
      
      Title: #{title}
      Type: #{goal_type}
      Description: #{description}
      
      Success Criteria:
      #{success_criteria.to_json}
      
      Current Metrics:
      #{current_metrics.to_json}
      
      Target Metrics:
      #{target_metrics.to_json}
      
      Suggested Actions:
      #{suggested_actions.to_json}
      
      Complete this goal and report your results.
    PROMPT
  end

  def find_best_executor
    # Use Smart Router to find best agent for this goal type
    if defined?(Agents::SmartRouterService)
      router = Agents::SmartRouterService.new(entity: entity, user: entity.users.first)
      results = router.find_best_agent(task_description: "#{goal_type}: #{title}")
      if results.any?
        AgentPlugin.find_by(slug: results.first[:agent_slug])
      end
    end
  end
end
