# == Landing Page Model
#
# Landing pages are standalone web pages designed for marketing campaigns.
# They are generated by AI (Claude) as complete HTML and can be used to:
# - Capture leads through contact forms
# - Promote products or services
# - Support marketing campaigns
# - Drive conversions
#
# == Fields:
# - title: The page title/name (required)
# - slug: URL-friendly identifier (auto-generated from title, must be unique)
# - subdomain: Unique subdomain for direct access (e.g., mypage.lp.amoslabs.com)
# - description: Brief description of the page purpose
# - html_content: Complete HTML content generated by Claude (can include forms, CSS, JS)
# - status: Page status - "draft", "published", or "archived"
# - user_id: Creator of the page (required)
# - entity_id: Organization/entity the page belongs to (required)
# - campaign_id: Optional campaign association
#
# == Relationships:
# - belongs_to :user (creator)
# - belongs_to :entity (organization)
# - belongs_to :campaign (optional - for campaign-specific pages)
# - has_many :landing_page_chat_messages (chat interactions)
# - has_many :landing_page_versions (version history)
#
# == Usage Examples:
# - Lead generation: "Download our free guide" with contact form
# - Product promotion: "30-day free trial" with signup form
# - Event registration: "Register for webinar" with registration form
# - Newsletter signup: "Join our newsletter" with email capture
#
# == Subdomain Access:
# Each landing page automatically gets a unique subdomain URL like:
#   mypage.lp.amoslabs.com
# The subdomain is auto-generated from the title on creation.
#
class LandingPage < ApplicationRecord
  include HasCustomFields
  include WorkflowTriggerable

  # Reserved subdomains that cannot be used for landing pages
  RESERVED_SUBDOMAINS = %w[
    www app api admin mail ftp smtp pop imap ns1 ns2 mx
    assets cdn static localhost dev staging test preview
    support help docs blog shop store status dashboard
    login signup register auth oauth callback webhook
    graphql rest socket ws wss ssl secure
  ].freeze

  # === ASSOCIATIONS ===
  belongs_to :user
  belongs_to :entity
  belongs_to :campaign, optional: true

  # Chat and versioning
  has_many :landing_page_chat_messages, dependent: :destroy
  has_many :landing_page_versions, dependent: :destroy

  # Form submissions
  has_many :landing_page_submissions, dependent: :destroy

  # Store accessors for metadata JSONB field
  store_accessor :metadata, :dsl_content, :generated_with, :generator_version, :generated_at, :page_font

  # Remove rich text sections - we're using html_content now
  # has_many :rich_text_sections, dependent: :destroy # REMOVED

  # Remove Active Storage - we're putting images directly in HTML
  # has_one_attached :hero_image # REMOVED

  # === VALIDATIONS ===
  validates :title, presence: true, length: { maximum: 255 }
  validates :slug, presence: true, uniqueness: true,
            format: { with: /\A[a-z0-9\-_]+\z/,
                      message: "can only contain lowercase letters, numbers, hyphens, and underscores" }
  validates :status, inclusion: { in: %w[draft published archived] }
  validates :description, length: { maximum: 1000 }
  validates :html_content, length: { maximum: 500_000 } # ~500KB limit for HTML

  # Subdomain validation - unique subdomain for direct access (e.g., mypage.lp.amoslabs.com)
  validates :subdomain,
            uniqueness: { case_sensitive: false, allow_nil: true },
            format: {
              with: /\A[a-z0-9][a-z0-9\-]{0,61}[a-z0-9]?\z/,
              message: "can only contain lowercase letters, numbers, and hyphens (cannot start or end with hyphen)",
              allow_nil: true
            },
            length: { minimum: 2, maximum: 63, allow_nil: true }
  validate :subdomain_not_reserved

  # === CALLBACKS ===
  before_validation :generate_slug, if: -> { slug.blank? && title.present? }
  before_validation :generate_subdomain, if: -> { subdomain.blank? && title.present? }

  # === SCOPES ===
  scope :published, -> { where(status: "published") }
  scope :drafts, -> { where(status: "draft") }
  scope :archived, -> { where(status: "archived") }
  scope :by_entity, ->(entity_id) { where(entity_id: entity_id) }
  scope :by_campaign, ->(campaign_id) { where(campaign_id: campaign_id) }
  scope :recent, -> { order(updated_at: :desc) }
  scope :by_subdomain, ->(subdomain) { where(subdomain: subdomain.downcase) }
  # Ownership scopes for security
  scope :accessible_by, ->(user, entity) { where(user: user, entity: entity).or(where(entity: entity)) }
  scope :editable_by, ->(user, entity) { where(user: user, entity: entity) }
  
  # === OWNERSHIP METHODS ===
  
  # Check if a user can view this landing page
  def accessible_by?(user, entity = nil)
    return false unless user
    return true if user.admin?
    
    # User must belong to the same entity
    entity ||= user.current_entity
    self.entity_id == entity&.id
  end
  
  # Check if a user can edit this landing page
  def editable_by?(user, entity = nil)
    return false unless user
    return true if user.admin?
    
    entity ||= user.current_entity
    # Must belong to same entity AND (be the creator OR entity admin)
    self.entity_id == entity&.id && (self.user_id == user.id || user.entity_admin?)
  end
  
  # Class method to find with ownership check
  def self.find_editable(id, user:, entity:)
    page = find_by(id: id, entity: entity)
    raise ActiveRecord::RecordNotFound, "Landing page not found" unless page
    raise SecurityError, "Not authorized to edit this landing page" unless page.editable_by?(user, entity)
    page
  end

  # === PUBLIC METHODS ===

  # Use slug as the URL parameter instead of ID
  def to_param
    slug
  end

  # Get the subdomain URL for direct access (e.g., https://mypage.lp.amoslabs.com)
  # @return [String, nil] Full subdomain URL or nil if no subdomain assigned
  def subdomain_url
    return nil unless subdomain.present?

    host = SubdomainConfig.landing_page_host
    protocol = Rails.env.production? ? "https" : "http"
    "#{protocol}://#{subdomain}.#{host}"
  end

  # Get the full URL for this landing page
  # Prefers subdomain URL if available, falls back to slug-based URL
  # @param base_url [String] Base URL (e.g., "https://mysite.com")
  # @return [String] Full URL to the landing page
  def full_url(base_url = nil)
    # Prefer subdomain URL if available
    return subdomain_url if subdomain.present?

    # Fall back to slug-based URL
    if base_url.present?
      "#{base_url}/landing/#{slug}"
    else
      "/landing/#{slug}"
    end
  end

  # Check if the page has any content
  # @return [Boolean] true if html_content is present
  def has_content?
    html_content.present?
  end

  # Get a preview/summary of the page for listings
  # @return [Hash] Summary data for display
  def preview_data
    {
      id: id,
      title: title,
      slug: slug,
      subdomain: subdomain,
      subdomain_url: subdomain_url,
      description: description&.truncate(100),
      status: status,
      has_content: has_content?,
      created_at: created_at,
      updated_at: updated_at,
      campaign_name: campaign&.name,
      url: full_url
    }
  end

  # Mark the page as published
  def publish!
    update!(status: "published")
  end

  # Mark the page as archived
  def archive!
    update!(status: "archived")
  end

  # Check if page is published and ready for visitors
  def live?
    status == "published" && has_content?
  end

  # Create a backup version of the current content for rollback purposes
  # @param description [String] Description of why this backup was created
  # @return [LandingPageVersion] The created version record
  def create_version_backup(description = "Content backup")
    return nil unless has_content?

    landing_page_versions.create!(
      content: { html_content: html_content },
      headline: title, # Store title as headline for compatibility
      ai_applied: true,
      description: description
    )
  end

  # Restore from a version that contains html_content
  # @param version [LandingPageVersion] The version to restore from
  # @return [Boolean] Success status
  def restore_from_version(version)
    return false unless version.content.is_a?(Hash) && version.content["html_content"].present?

    # Create backup of current state
    create_version_backup("Before restore to: #{version.description}")

    # Restore the html_content
    update!(html_content: version.content["html_content"])

    # Create rollback record
    landing_page_versions.create!(
      content: { html_content: version.content["html_content"] },
      headline: title,
      ai_applied: false,
      description: "Restored from version: #{version.description} (#{version.created_at.strftime('%Y-%m-%d %H:%M')})"
    )

    true
  rescue => e
    Rails.logger.error "Failed to restore landing page version: #{e.message}"
    false
  end

  private

  # Generate a unique slug from the title
  def generate_slug
    base_slug = title.parameterize
    self.slug = base_slug

    # Ensure uniqueness
    counter = 1
    while LandingPage.where(slug: slug).where.not(id: id).exists?
      self.slug = "#{base_slug}-#{counter}"
      counter += 1
    end
  end

  # Generate a unique subdomain from the title
  # Follows same pattern as generate_slug but for subdomains
  def generate_subdomain
    # Parameterize and truncate to leave room for counter suffix
    base_subdomain = title.parameterize[0..50]

    # Ensure it starts and ends with alphanumeric (no leading/trailing hyphens)
    base_subdomain = base_subdomain.gsub(/\A-+|-+\z/, "")
    return if base_subdomain.blank? || base_subdomain.length < 2

    candidate = base_subdomain
    counter = 1

    # Ensure uniqueness and not reserved
    while LandingPage.where(subdomain: candidate).where.not(id: id).exists? ||
          RESERVED_SUBDOMAINS.include?(candidate.downcase)
      candidate = "#{base_subdomain}-#{counter}"
      counter += 1
    end

    self.subdomain = candidate.downcase
  end

  # Validate that subdomain is not in reserved list
  def subdomain_not_reserved
    return unless subdomain.present?

    if RESERVED_SUBDOMAINS.include?(subdomain.downcase)
      errors.add(:subdomain, "is reserved and cannot be used")
    end
  end
end
